### ISSUE TITLE
View dataset details

### ISSUE THREAD

**Issue by osahon-okungbowa** [transport-data/tdc-data-portal#101]
When i am on the TDC portal and i visit a specific dataset (either directly through the url, clicking on a link, searching etc), i want to see metadata and data for the specific dataset, so that i can know more about the dataset and download any data on the dataset.
Hint: implementation for [this design](https://www.figma.com/proto/fhRAGjVCFOvcjenVTX0Ko6/TDC?node-id=513-34490&node-type=FRAME&t=R30kSWgwuTFdsRKI-0&scaling=min-zoom&content-scaling=fixed&page-id=0%3A1&starting-point-node-id=5%3A1091)

## Tasklist (TBD)
- (developer to complete)
- write integration tests
- write user guide documentation

## Acceptance Criteria
Given i visit a specifc dataset on the TDC portal, then:
- [x] i see the dataset title
- [x] i see the dataset description and other agreed upon metadata in the Overview from the [Figma Design](https://www.figma.com/proto/fhRAGjVCFOvcjenVTX0Ko6/TDC?node-id=513-34490&node-type=FRAME&t=R30kSWgwuTFdsRKI-0&scaling=min-zoom&content-scaling=fixed&page-id=0%3A1&starting-point-node-id=5%3A1091)
- [ ] ~~i see a tabular preview of the dataset data in the Dataset tab~~
- [x] i see other metadata in the Metadata tab
- [ ] ~~i see a link to existing discussions and a button to create new discussions when i view the Discussions tab~~
- [x] i see a list resources and documents which i can download when i visit the Downloads tab

**Comment by luccasmmg** [comment]
Tests https://github.com/transport-data/tdc-data-portal/pull/147/files#diff-c6e5d33be6e21a694c3eda38a7bccc808d939e231c6be9293105487ed09fe81c

**Comment by luccasmmg** [comment]
Docs https://github.com/transport-data/tdc-data-portal/tree/main/docs/datasets#datasets-page

**Comment by Uchechukwu-Onye-Igbo** [comment]
QA Feedback

@luccasmmg can you share with me a dataset where i can download from? because so far, i cannot download anything yet.

**Comment by Uchechukwu-Onye-Igbo** [comment]
### Feedback on the "Access by API” collapsible

- For each resource within a dataset, there should be a collapsible section labeled "Access by API"
- When expanded, this section should display detailed API information related to that specific dataset resource.
- Users can toggle the collapsible to show or hide the advanced API details as needed for each resource.

@luccasmmg please take note

**Comment by Uchechukwu-Onye-Igbo** [comment]
### Citation Template

[Link](https://gizonline.sharepoint.com/:w:/r/sites/TransportAmbitionwithguests-TDCI-CKANDevelopment/Freigegebene%20Dokumente/TDCI%20-%20CKAN%20Development/Templates-Citation-Styles.docx?d=w661e9e7728084f05b08f2d53e3e5bfbc&csf=1&web=1&e=I6rbej)

CC @luccasmmg @nicolas-becker

**Comment by luccasmmg** [comment]
Both of those are done

**Comment by Uchechukwu-Onye-Igbo** [comment]
### QA Feedback

@luccasmmg please take a look at the following points and fix them

- The contributors list has a many names (possibly all the people in the portal), some are duplicates. I dont recognize the name "Abdelrahman Hegazy". "ckan_admin" should be hidden (like we agreed)
- The reference period dates is in a non-English language.
- Citation concerns [Document](https://gizonline.sharepoint.com/:w:/r/sites/TransportAmbitionwithguests-TDCI-CKANDevelopment/_layouts/15/Doc.aspx?sourcedoc=%7B661E9E77-2808-4F05-B08F-2D53E3E5BFBC%7D&file=Templates-Citation-Styles.docx&action=default&mobileredirect=true)
    - the static text [Data set] is missing in APA
    - BibTex: the first line of the syntax is missing. Also the order implemented is wrong. Please refer to the document linked above

**Comment by luccasmmg** [comment]
Done

**Comment by nicolas-becker** [comment]
Generally looks good already. A few comments:

- The titles are partially hidden (lower part of 'g's or 'y's). See, e.g.: https://tdc-data-portal.vercel.app/@transport-data-commons/freight-transport-activity-water-jrc-idees. Please fix
- The metadata overview section is missing "Region" 
- Would be nice to have the tags implemented as icons, such as in the Figma, for improved recognizability: 
![image](https://github.com/user-attachments/assets/499775e9-8a50-4286-a2b1-8d70fb71e421)
- Regarding citations, please include the spaces between the differents components. Also, please implement italics or quotation marks for the titles as indicated in the template. Insert the brackets around the years in APA and Harvard style. Thank you
- How are multiple authors handled in the citation? In this dataset https://tdc-data-portal.vercel.app/@test-organization/new-tester it seems like only the first one is included (in this case Uche)
. It looks like the ckan_admin is still indicated as author in the metadata overview: eg.: https://tdc-data-portal.vercel.app/@dry-run/qa-new

**Comment by Uchechukwu-Onye-Igbo** [comment]
> * The tabs in the citation section are "moveable", i.e. it's possible to drag them. I am not sure if this is the intended behaviour. Also, if I remember correctly, we had agreed with @Uchechukwu-Onye-Igbo to include the BibTex section as another tab to the upper window and drop the second one.

Hi @nicolas-becker we did not agree to do this though. it was an idea you brought up and later dropped. but sure we can make it so.

**Comment by nicolas-becker** [comment]
Hi @Uchechukwu-Onye-Igbo, you're right, I just checked the meeting notes again: "Datopian to start working with APA and BibTex for now in separate windows." As we did not include any further tabs in the code integration window, I think we can just merge the two windows to save space. But this of course is low prio. Thank you!

More important it would be to replace the download icon with a link icon (e.g. :link: ) on the download page, when the resource is a link, such as here: https://tdc-data-portal.vercel.app/ITF-OECD/airport-density-avia-itf-oecd

**Comment by nicolas-becker** [comment]
Thanks @luccasmmg. 

> We are using the creator_user name, do you want to use the contributors as the authors? 

Yes please. At which point are the contributors added to the dataset's metadata? Or does this field track the users that edit the dataset?

**Comment by luccasmmg** [comment]
> Yes please. At which point are the contributors added to the dataset's metadata? Or does this field track the users that edit the dataset?

It track the users that edit the dataset

**Comment by nicolas-becker** [comment]
Also please refer to this point:

> It looks like the ckan_admin is still indicated as author in the metadata overview: eg.: https://tdc-data-portal.vercel.app/@dry-run/qa-new

Specially regarding the citation:
![Image](https://github.com/user-attachments/assets/65a4e22e-746f-4d29-90d3-128cfa304866)
Please indicate the TDC as author in these cases, when ckan_admin is the sole contributor, as it partially seems to be handled in the BibTex entry:
![Image](https://github.com/user-attachments/assets/fc637e7f-2cbc-4bc4-a034-bb33fe126a35)

@luccasmmg

**Comment by luccasmmg** [comment]
Filtering ckan_admin should be live in about 10 minutes 

![image](https://github.com/user-attachments/assets/22ba54f8-ad6f-477f-b9d9-8fa100b823fe)

**Comment by nicolas-becker** [comment]
@luccasmmg Nice! Seems to work except for the MLA case:

![image](https://github.com/user-attachments/assets/f8c60aa3-4f21-4ee8-8fc4-2688267f7aaa)

Also, the initials of the name contain both the first and the last name (Mateus, L.M.). Instead this should only contain the first name (Mateus, L.), is that possible? Otherwise just keep the entire first name (Mateus, Luccas).

I've just noticed that of course citing the autor will only be possible when the user provides their full name on the platform. So,
a) in which cases will the full name appear? Probably only when the user provides his full name on GitHub?
b) is it possible to filter for these cases? Otherwise we would just have to add the organization as author in general, to prevent citations like this:
![image](https://github.com/user-attachments/assets/603bbcb4-cb2f-40e2-878b-82bfcc10c6f7)

**Comment by Uchechukwu-Onye-Igbo** [comment]
> @luccasmmg Nice! Seems to work except for the MLA case:
> 
> ![image](https://private-user-images.githubusercontent.com/56161155/385003704-f8c60aa3-4f21-4ee8-8fc4-2688267f7aaa.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE1OTI1NDAsIm5iZiI6MTczMTU5MjI0MCwicGF0aCI6Ii81NjE2MTE1NS8zODUwMDM3MDQtZjhjNjBhYTMtNGYyMS00ZWU4LThmYzQtMjY4ODI2N2Y3YWFhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTE0VDEzNTA0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk1YjlkM2I1ODY0NThjNTFmMGZiMGI0MzRiNDRmYzEwMWJkMWY1YTI5ZTY0MzFmMDEwODY5MjU5NTE0MWY5NTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.aJKSBarEqXWRN8ibtIe5DAUHlLoabEh6RDvRzaaVywE)
> 
> Also, the initials of the name contain both the first and the last name (Mateus, L.M.). Instead this should only contain the first name (Mateus, L.), is that possible? Otherwise just keep the entire first name (Mateus, Luccas).
> 
> I've just noticed that of course citing the autor will only be possible when the user provides their full name on the platform. So, a) in which cases will the full name appear? Probably only when the user provides his full name on GitHub? b) is it possible to filter for these cases? Otherwise we would just have to add the organization as author in general, to prevent citations like this: ![image](https://private-user-images.githubusercontent.com/56161155/385006640-603bbcb4-cb2f-40e2-878b-82bfcc10c6f7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE1OTI1NDAsIm5iZiI6MTczMTU5MjI0MCwicGF0aCI6Ii81NjE2MTE1NS8zODUwMDY2NDAtNjAzYmJjYjQtY2IyZi00MGUyLTg3OGItODJiZmNjMTBjNmY3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTE0VDEzNTA0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc0OTEzN2ZhOGRjODFiOTYyZGYxOWVlMGIzMzgzZDIwOWRkODhlYmU5NTg0MjU0MmFjNmYxNTkwYjlhNTNjNzImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.HQt8P6BHQgPcyFtAGqAd00qPPOWUo8T8b13QvkiEQRs)

hello @luccasmmg please take a look at this

**Comment by luccasmmg** [comment]
@nicolas-becker like this?
![image](https://github.com/user-attachments/assets/147da2ea-b76f-487d-9ede-b94d4f7f2641)
Flagging that i noticed that i noticed that Chicago is wrong but already made a fix to it, should be getting deployed in a couple of minutes

I've just noticed that of course citing the autor will only be possible when the user provides their full name on the platform. So,
a) in which cases will the full name appear? Probably only when the user provides his full name on GitHub?
You are correct
b) is it possible to filter for these cases? Otherwise we would just have to add the organization as author in general, to prevent citations like this:
That depends on what you want to do, if there are 3 authors for example, 2 of them are ok, 1 is not, do we

- Filter out the wrong one
- Replace everything with TDC
- Somethin else which im not aware?

**Comment by nicolas-becker** [comment]
Hi @luccasmmg perfect thanks!

Yes, in case there are multiple users, please filter the once that are mentioned with their real name and cite them. E.g, here you would just mention Leonardo, please:
https://tdc-data-portal.vercel.app/@test-organization/new-tester

If no real name is indicated, please use the data provide Organization as Author, so this should be the default.

Let me know when you have done this for me to close the issue. Thanks

**Comment by luccasmmg** [comment]
@nicolas-becker check again
![image](https://github.com/user-attachments/assets/cd1172ac-ebbe-43bd-b06f-92b57298f485)

**Comment by nicolas-becker** [comment]
@luccasmmg looks fine now for this example, thanks. Could you please check again for the default option with the Org? For example here, I am getting [object Object] as author:

https://tdc-data-portal.vercel.app/Test%20Org/ab

**Comment by luccasmmg** [comment]
Fixed, typo on my part
![image](https://github.com/user-attachments/assets/830edf17-5209-4bb3-967f-7128826d8b64)
