### ISSUE TITLE
Implement Backend Functionality for Dataset Approval Requests

### ISSUE THREAD

**Issue by Uchechukwu-Onye-Igbo** [transport-data/tdc-data-portal#131]
When a data contributor submits a data request, I want the request to be sent to an admin for review, So that the admin can either approve or reject the data request, And I can subsequently inform the data contributor of the status of their request, Ensuring that only well-cleaned and appropriate data is available for portal users.

## Tasklist (TBD - updated by the developer)
* [add task]

## Acceptance Criteria

An admin can,
* [x] view a list of all pending dataset requests on the portal.
* [x] Approve/reject a dataset request by click of a button, making it live on the portal.
* [x] can provide a comment explaining the decision of approval or rejection.
* [x] Decision on any data request will be notified the data contributors. 
* [x] Receive an email about the data request from data contributors 

Data contributors can,
* [x] view all pending requests on "My dataset" and "my organisation" page of the dashboard.
* [x] Other user in their organisation can see the dataset request they made in their respective "my organisation" pages
* [x] cannot edit the dataset when it is in review
* [x] will get update in my newsfeed when my dataset has been a approved or rejected

**Comment by demenech** [comment]
Moving to QA.

Docs can be found at: https://github.com/transport-data/tdc-data-portal/tree/main/docs/approval-workflow

**Comment by nicolas-becker** [comment]
When testing the functionality with @willy1989cv I've notices that the datasets listed in the Request tab sometimes disappear and appear only after reloading. A similar behaviour has been observed in My Datasets tab, as discussed with @Gutts-n

**Comment by nicolas-becker** [comment]
More critical is that the user (@willy1989cv ) did not receive the message I had sent him during rejection of the dataset.

**Comment by Gutts-n** [comment]
@demenech in addition to the report that the e-mail was not sent to the user, there is also [this comment here](https://github.com/transport-data/tdc-data-portal/issues/49#issuecomment-2469126002)

**Comment by nicolas-becker** [comment]
Hi @Gutts-n ,

unfortunately the My Dataset listing appears to still not be stable, even for a dataset with more than 2 chars:

https://github.com/user-attachments/assets/4b4ad863-868a-4122-9b17-8dff5373a0f9

**Comment by Gutts-n** [comment]
@nicolas-becker I tried to limit the CKAN to use one specific replica to index the datasets. Could you please test the platform by creating and editing datasets and give me feedback if the problem is fixed or not? I couldn't create a dataset that has the same problem, so I'm not able to do it.

**Comment by demenech** [comment]
@nicolas-becker I'm investigating this issue with approved and rejected emails.

It works fine locally, we tested on dev when the feature was developed and it worked fine as well, with no errors on the log. I suspect it might be the SMTP server that is blocking certain templates. I'll continue investigating.

**Comment by nicolas-becker** [comment]
@Gutts-n it seems to work now. I'll let you know if I experience the issue again.

One more thing, could you delete or deactivate the `save draft` button for datasets that have already been sent for approval? Otherwise the user triggers an error if he tries to save as draft. Thanks!

**Comment by Uchechukwu-Onye-Igbo** [comment]
> @Gutts-n it seems to work now. I'll let you know if I experience the issue again.
> 
> One more thing, could you delete or deactivate the `save draft` button for datasets that have already been sent for approval? Otherwise the user triggers an error if he tries to save as draft. Thanks!

we have a fix coming. @willy1989cv

**Comment by willy1989cv** [comment]
> One more thing, could you delete or deactivate the save draft button for datasets that have already been sent for approval? Otherwise the user triggers an error if he tries to save as draft. Thanks!

Done. @nicolas-becker @Uchechukwu-Onye-Igbo

**Comment by demenech** [comment]
hello @nicolas-becker 

I'm deploying a fix for the emails, it should work fine now.

CC: @osahon-okungbowa @Uchechukwu-Onye-Igbo

**Comment by nicolas-becker** [comment]
Thanks to both! I'll test again

**Comment by nicolas-becker** [comment]
Email notifcation are working perfectly now, many thanks! @demenech

**Comment by nicolas-becker** [comment]
Email notifcation are working perfectly now, many thanks! @demenech
