### ISSUE TITLE
Design harmonised Metadata schema for the portal

### ISSUE THREAD

**Issue by Uchechukwu-Onye-Igbo** [transport-data/tdc-data-portal#15]
When creating datasets, organisations and groups, I want to have a standardized metadata schema, so that I can have data consistency across the portal and make datasets easier to understand and use.

## Tasklist

- [ ] Analyze the material
  - [x] The links they provided
    - [ ] https://ec.europa.eu/eurostat/cache/metadata/en/avia_if_esms.htm
    - [ ] https://github.com/transport-data/tools/pull/21 
  - [x] The data sources (https://docs.google.com/spreadsheets/d/1L-Xsql6DZPAz-9HzmvLB6ct_MH7aA9fd/edit?gid=1950324098#gid=1950324098)
  - [x] DCAT-AP (https://semiceu.github.io/DCAT-AP/releases/3.0.0/)
  - [x] The mock-ups (https://www.figma.com/design/fhRAGjVCFOvcjenVTX0Ko6/TDC?node-id=286-45417&node-type=FRAME&t=YmTay79pjXVwZJ6p-0)
- [ ] Create a metadata schema based on the material above 

## Acceptance Criteria
* [ ] We have designed a metadata schema
* [x] We have designed a metadata schema that is compliant to DCAT-AP
* [ ] That the metadata schema design reflects the specific requirement of the platform
* [x] The client has reviewed and approved the metadata schema
* [ ] That we have documentation for the metadata schema design

**Comment by demenech** [comment]
**Schema:** https://docs.google.com/spreadsheets/d/1G_Eq4T5rdolKq3uaFczbLAQfSwFzwwX9XVhjflll5gk/edit?gid=0#gid=0

**Fields in green = seem straightforward
Fields in yellow = have to be discussed**

## Next steps:

- [ ] Team review + discussion; clarification of the fields that are uncertain;
- [ ] Client review and approval
- [ ] Transform the spreadsheet into a ckanext-scheming schema
- [ ] Install ckanext-dcat and validate DCAT compliance

CC: @Uchechukwu-Onye-Igbo @anuveyatsu @osahon-okungbowa

**Comment by osahon-okungbowa** [comment]
@luccasmmg @Gutts-n please review this Spreadsheet

> **Schema:** https://docs.google.com/spreadsheets/d/1G_Eq4T5rdolKq3uaFczbLAQfSwFzwwX9XVhjflll5gk/edit?gid=0#gid=0
> 
> **Fields in green = seem straightforward Fields in yellow = have to be discussed**

**Comment by demenech** [comment]
Questions to the client (raised during sync between me and Anuar):

- Sector, service, and mode - What are the possible values for each of these fields?
- How can we map data sources to datasets? Is it one dataset per row? Or does it depend on the data source?

@Uchechukwu-Onye-Igbo please let's add that as discussion points for our next meeting.

**Comment by khaeru** [comment]
Hi all—some comments and extra information/requirements here from the TDCI side. I number the points for easier reference:

1. TDCI has decided to, as far as possible, use SDMX for data and metadata exchange. If the Datopian team are not already familiar (or only partly) with SDMX, please give some indication of your level of knowledge, and I can point to learning resources.
   - As you may or will know, SDMX standards *per se* provide a **general information model (IM)** but not **specific instructions** on how to use it.
   - For instance, the IM gives the notion of a Metadata Structure Definition containing multiple (hierarchical) Metadata Attributes; and then a Metadata Set containing multiple Metadata Reports, each with Reported Attribute values corresponding to the defined structure.
   - But the standards do not say *what the metadata attributes should be*; that is application-specific.
   - Likewise they give the notion of a Data Structure Definition with certain identified dimensions associated with concepts and code lists, but do not say what dimensions any particular DSD should have.
3. This is why we have looked to **Eurostat as an example of best-practice**. I am glad the first two links in the description above have reached you. At https://ec.europa.eu/eurostat/cache/metadata/en/avia_if_esms.htm, in particular:
   - Use the "Download" link to retrieve a ZIP file that contains **both** SDMX-ML documents for the metadata structure (`ESMS_MSD.msd.xml`) *and* one concrete metadata report (`avia_if_esms.sdmx.xml`), the same one displayed as HTML.
   - The metadata structure includes a scheme defining the concepts like, for example, REL_POL_US_AC, and showing that this should be given as a sub-attribute to REL_POLICY. The metadata report, again, matches this structure.
4. We anticipate that **the detail and sophistication of metadata handled by TDCI will evolve over time**:
   - In this early phase, we will use a *reduced/simplified* but analogous metadata structure, informed by the Eurostat/ESMS example. This is what is being developed at transport-data/tools#21.
   - However, the set of metadata will grow and become more carefully resolved as needs dictate. Over time, TDCI's metadata structure(s) may more closely align with ESMS, have an overlapping set of attributes, and have similar degree of detail.
5. Based on this anticipated usage, it is important to **have or be prepared for** interoperability between the CKAN instance and an evolving TDCI SDMX metadata structure. I do not have experience with CKAN, but for example I guess:
   - Metadata attached to particular CKAN records/describing files should map 1:1, and with minimal transformation, to SDMX-structured metadata. So for instance your attached Google spreadsheet ("TDC Metadata Schema") has in cell B12 "API field name: geographies".
     - If this ID, "geographies", is hard-coded in CKAN, then it is important to identify that this is the same as, or distinct from, urn:sdmx:org.sdmx.infomodel.conceptscheme.Concept=ESTAT:SDMX_CDC(3.0).REF_AREA in the XML file mentioned above.
     - If the ID "geographies" is not hard-coded in CKAN, then possibly using REF_AREA or a better choice from existing SDMX applications may be easier.
   - This will ease flowing SDMX (meta)data into CKAN, and also transforming user-generated content/records on the CKAN instance into SDMX for further use.
   - If it is possible to “round-trip” metadata structure information (the CKAN "metadata schema/fields" to an SDMX metadata structure definition and attributes, or vice versa) then we can ensure the two remain closely aligned.
   - If CKAN has particular limitations (e.g. if adding, removing, or altering metadata "fields" is costly or not possible), then it would be good to know these in advance and have a strategy that allows the CKAN schema to keep up with the TDCI SDMX metadata structure.

That is probably a lot to digest, so I will leave it there for now. Happy to respond to clarifying questions.

**Comment by khaeru** [comment]
> * Sector, service, and mode - What are the possible values for each of these fields?

@demenech for SERVICE and MODE see https://github.com/transportenergy/database/blob/main/item/structure/base.py. These are partial lists and should be eventually moved to/maintained in the transport-data/tools repo. Others include for example the list used by ITF-OECD:

```python
>>> import sdmx
>>> message = sdmx.Client("OECD").get("codelist", "CL_TRANSPORT_MODE")
>>> codelist = message.codelist["CL_TRANSPORT_MODE"]
>>> print("\n".join(map(repr, sorted(cl.items.values()))))
<Code AIR: Air>
<Code COASTAL: Coastal shipping>
<Code HIRING: For hire and reward>
<Code IWW: Waterways>
<Code MAR: Maritime>
<Code MOTORWAYS: Motorways>
<Code OWN: On own account>
<Code PIPE: Pipeline>
<Code RAIL: Rail>
<Code ROAD: Road>
<Code TOT_INL: Inland>
<Code _T: Total>
<Code _Z: Not applicable>
```

**Comment by demenech** [comment]
Hi @khaeru 

Thank you very much for this very detailed response.

## Interoperabity

In terms of interoperability, we are thinking of doing something similar to what [ckanext-dcat](https://github.com/ckan/ckanext-dcat) does with DCAT-AP, but for SDMX following the definition you provided.

`ckanext-dcat` maps CKAN fields to DCAT fields following this table https://github.com/ckan/ckanext-dcat/blob/master/docs/mapping.md. For example, it specifies that the CKAN `tags` field is associated with DCAT-AP `dcat:keywords` field.

Then, `ckanext-dcat` allows for interoperability by providing a `/data.json` endpoint with the CKAN datasets metadata converted to DCAT-AP.

For TDC, we would create a `ckanext-sdmx` extension that behaves in a similar way.

We could use the same metadata schema yaml file that we are using now (https://github.com/transport-data/tdc-data-portal/blob/main/src/ckanext-tdc/ckanext/tdc/schemas/dataset.yaml) to add information on how the conversion to SDMX should behave (e.g. CKAN `geographies` -> `REF_AREA`), and `ckanext-sdmx` would read that and reflect the specification into and endpoint used for SDMX exports. 

We believe this approach is very flexible for future extension and aligned with your point:

> If it is possible to “round-trip” metadata structure information (the CKAN "metadata schema/fields" to an SDMX metadata structure definition and attributes, or vice versa) then we can ensure the two remain closely aligned.

**Comment by khaeru** [comment]
@demenech I think that sounds like a great approach and a good way to build on your prior work.

The key distinction, as far as I can see:
- DCAT-AP (I am not super familiar, but going from the link in the description above) prescribes *specific lists* of "entities" (Main entities, supportive entities).
- SDMX *per se* does not prescribe any metadata attributes, their names, etc. Only *particular applications of SDMX* will set up specific lists of attributes and concepts.

So this means one can't map CKAN fields to "SDMX" *in general*, but to *one particular* SDMX metadata structure. For now this can be a fixed TDCI metadata structure, but I'm just motivating to future-proof by allowing it to someday be a different/evolved TDCI-defined structure, or one defined by someone else.

**Comment by demenech** [comment]
@khaeru thanks, it's clear. I was referring to mapping to this application-specific SMDX metadata structure. And definitely, we'll make sure to keep it flexible and future-proof, with supporting technical documentation as well.

Also, one other thing I'm wondering, do you have any sort of automatic validator for the metadata structure of the Eurostat/ESMS example? Perhaps a Python script or something like that?

**Comment by khaeru** [comment]
Not exactly, but I will try to whip up an example this morning.

**Comment by demenech** [comment]
great stuff @khaeru 
Thank you very much!

**Comment by osahon-okungbowa** [comment]
closing this as there is consensus on the metadata schema design

**Comment by demenech** [comment]
hey @khaeru 

I've been looking into this for a couple days and I think I have a better understanding of what you meant with your previous messages.

At first, I was thinking that what we wanted was to convert the datasets metadata to ESMS, but after a while I realized that this would require many changes to our current metadata schema.

Then, after looking more carefully into the PR you shared, I realized you are creating your own MS (as you had pointed out before but I couldn't understand), whose current state is https://github.com/transport-data/tools/pull/21/files#diff-a920973cf3c3bdb7578f9a3e8784fb624988297308cd07162659a7da2dceb014R20 and noticed that there is this test data https://github.com/transport-data/tools/pull/21/files#diff-7749901cb32bf79531305a9b41ff5cc36243b0c540c945a9a9ebbcc06e6ebfd6 as well.

1) Am I right in assuming that it makes more sense to convert the datasets metadata to the MS linked above?

I then realized that controlling the conversion based on the dataset schema yaml file wouldn't work. Reason is that for many attributes we can't really do a 1:1 conversion, and rules for different attributes could vary e.g. `DATA_PROVIDER` could take many different forms depending on what metadata is available.

With that in mind, I created a simple converter class that allows the use of an "attribute" decorator to describe how conversion should happen. E.g.:

```python
class TdciConverter(BaseConverter):
    def __init__(self, data_dict):
        super().__init__(data_dict)

    @attribute("DATAFLOW")
    def get_dataflow(self):
        return self.data_dict.get("id")

    @attribute("DATA_PROVIDER")
    def get_data_provider(self):
        sources = self.data_dict.get("sources", [])
        log.error(sources)
        if len(sources) > 0:
            return sources[-1].get("title")
        return None

    @attribute("URL")
    def get_url(self):
        sources = self.data_dict.get("sources", [])
        if len(sources) > 0:
            return sources[-1].get("url")
        return None

    @attribute("MEASURE")
    def get_measure(self):
        return self.data_dict.get("indicator")

    @attribute("UNIT_MEASURE")
    def get_units(self):
        units = self.data_dict.get("units")
        if isinstance(units, list):
            return ", ".join(units)
        if isinstance(units, str):
            return units

    @attribute("DATA_DESCR")
    def get_description(self):
        description = self.data_dict.get("notes")
        return description
```

**NOTE**: this implementation is not complete, not all TDCI MS rules are being followed

I think this would be the most flexible approach e.g if a new attribute is added to TDCI MS, all you would have to do is change this single file describing how the transformation from CKAN metadata to TDCI MS should happen.

In order to get the converted metadata for a dataset, you would simply `GET /api/3/action/package_show?id=my-dataset-id&output_format=tdci-sdmx`

And the result would be something like (dummy data):

```json
{
  "help": "http://ckan-dev:5000/api/3/action/help_show?name=package_show",
  "success": true,
  "result": {
    "DATA_PROVIDER": "Awesome Datasets",
    "DATAFLOW": "2b688a14-c743-42da-b902-be27769890be",
    "DATA_DESCR": "testing desription",
    "MEASURE": "testing indicator",
    "UNIT_MEASURE": "tonnes, kg",
    "URL": "https://datopian.com"
  }
}
```

2) Does this output format makes sense? I did it this way based on the `metadata_input.xlsx` file (https://github.com/transport-data/tools/pull/21/files#diff-7749901cb32bf79531305a9b41ff5cc36243b0c540c945a9a9ebbcc06e6ebfd6)

3) With this better understanding, I'm now wondering whether this conversion on the CKAN-side is really a requirement and is useful to you, OR what you were requesting is that we just have to ensure that the conversion is possible and as effortless as possible (e.g. we use equal or as close as possible controlled vocabularies and etc) and document the similarities between ESMS and CKAN metadata schema for future reference, so that you can retrieve the datasets metadata yourself and do the transformation on your end.

Thank you!

**Comment by khaeru** [comment]
> 1. Am I right in assuming that it makes more sense to convert the datasets metadata to the MS linked above?

Yes, for now. You can see the (prototype) metadata structure (MS) we are using in TDC is much simpler than the ESMS. We felt that, for now, the ESMS would be too burdensome for many stakeholders to fill out. In the long run, more sophisticated TDC activities would need more detailed and precise metadata, so we'd want to *evolve towards* parity with ESMS (more on that per your Q3 below). But not at this point.

> I think this would be the most flexible approach e.g if a new attribute is added to TDCI MS, all you would have to do is change this single file describing how the transformation from CKAN metadata to TDCI MS should happen.
>
> 2. Does this output format makes sense? I did it this way based on the metadata_input.xlsx file (https://github.com/transport-data/tools/pull/21/files#diff-7749901cb32bf79531305a9b41ff5cc36243b0c540c945a9a9ebbcc06e6ebfd6)

Yes, that seems like a fine format for the JSON. The extensible converter class seems like an elegant and future-proof solution.

> 3. With this better understanding, I'm now wondering whether this conversion on the CKAN-side is really a requirement and is useful to you, OR what you were requesting is that we just have to ensure that the conversion is possible and as effortless as possible (e.g. we use equal or as close as possible controlled vocabularies and etc) and document the similarities between ESMS and CKAN metadata schema for future reference, so that you can retrieve the datasets metadata yourself and do the transformation on your end.

"As seamless as possible" is indeed the high-level requirement…maybe I'd add "both now and in the future".

I have to apologize here—because this is a side activity for me, I have not had time to fully understand CKAN and its internals or to join the weekly stand-ups to ask directly. So some of my comments may be based on wrong guesses about what is/is not possible or realistic. If that's so, please correct me. As I understand:
- The base version of CKAN has a metadata schema with certain fields `a, b, c, …`.
- This can be customized by specifying further fields `d, e, f, …` or perhaps omitting some.

What I do not know:
- Is this schema *frozen* for the life of a CKAN instance?
- Or is it later possible (easy or hard) to add fields like `g, h, i`?

Ideally:
- As you say, let's try to clearly document the correspondence between CKAN built-in `a, b, c` and ESMS/TDC MS attributes `A, B, C` (e.g. if only names or minor formatting differs).
- Let's also specify (I think you've already done this) `d, e, f` to cover at least all the metadata attributes `D, E, F` in the TDC MS (no need to do all of ESMS).
- If CKAN's base metadata schema has some `q, x, z` that have no correspondents in ESMS/(current) TDC MS, that's fine, let's just list them explicitly.
- Let us please sketch/imagine what it would be like if TDCI stakeholders someday decide, "Ah, in order for us to [do a certain activity], we need to record `G, H, I` for some data sets/populate it for existing data sets, and display it in the data catalogue/web interface." In this situation:
  - How hard would it be to update the CKAN metadata schema to add corresponding `g, h, i`?
  - How hard would it be to adjust the API so that Python code in [transport-data/tools](https://github.com/transport-data/tools) is able to read/write/update these fields?

About code locations: it's fine if the CKAN API is just a "vanilla" one, and we use transport-data/tools as the place for code that does bidirectional transformation from SDMX (ESMS/TDC MS) to CKAN metadata. We had transport-data/tools#3 from a while ago, so we could simply add that, with your example class above as one direction of the transformation.

On the CKAN side, your judgment is better than mine, but I imagine if we have lots of complicated customizations these will be difficult to maintain and incrementally update in the future while the production instance is online. So perhaps that also weighs in favour of keeping the conversion out of CKAN *per se*.

Thanks for thinking carefully and thoroughly about our requirements here and for the illustrative examples. Much appreciated!

**Comment by demenech** [comment]
> Is this schema frozen for the life of a CKAN instance?
> Or is it later possible (easy or hard) to add fields like g, h, i?

CKAN comes with a default schema, but we use the [ckanext-scheming](https://github.com/ckan/ckanext-scheming) extension to customize the metadata schema.  This allows us to add, modify, or remove metadata fields by simply modifying a yaml file.

See https://github.com/transport-data/tdc-data-portal/blob/main/src/ckanext-tdc/ckanext/tdc/schemas/dataset.yaml#L5

You can change this file anytime and redeploy the instance, and the metadata schema will be updated.

The only extra effort I can foresee is that in order to allow users to make use of a new metadata field, you'd have to also implement an input for the new field on the admin application (Next.js, React) e.g. on the dataset create form (but note that the current dataset form has a good variety of input components and input examples, so it would very likely be a matter of copy/pasting and changing a few lines)

> As you say, let's try to clearly document the correspondence between CKAN built-in a, b, c and ESMS/TDC MS attributes A, B, C (e.g. if only names or minor formatting differs).
> Let's also specify (I think you've already done this) d, e, f to cover at least all the metadata attributes D, E, F in the TDC MS (no need to do all of ESMS).

Mappings:

TDC MS => https://github.com/transport-data/tdc-data-portal/blob/4367938e7715963ecbe5bdc1951c0fe2584150b1/docs/sdmx/README.md#mapping

ESMS => https://github.com/transport-data/tdc-data-portal/blob/4367938e7715963ecbe5bdc1951c0fe2584150b1/docs/sdmx/README.md#ckan-metadata-schema---esms

> How hard would it be to update the CKAN metadata schema to add corresponding g, h, i?

Changes to the yaml file + add a new field on the front end if needed (as described above)

> How hard would it be to adjust the API so that Python code in [transport-data/tools](https://github.com/transport-data/tools) is able to read/write/update these fields?

Regarding this, I'd like to recommend taking a look at the following endpoints:

- (Search/List) https://docs.ckan.org/en/2.11/api/#ckan.logic.action.get.package_search - The new fields would show up automatically on the response
- (Read) https://docs.ckan.org/en/2.11/api/#ckan.logic.action.get.package_show - The new fields would show up automatically on the response
- (Create) https://docs.ckan.org/en/2.11/api/#ckan.logic.action.create.package_create - Add the new field on the request body and you are good to go.
- (Update specific fields) https://docs.ckan.org/en/2.11/api/#ckan.logic.action.patch.package_patch - Same as the one above

Note that if the new fields are optional, it wouldn't even break the tools (but of course the new fields wouldn't be supported)

> On the CKAN side, your judgment is better than mine, but I imagine if we have lots of complicated customizations these will be difficult to maintain and incrementally update in the future while the production instance is online. So perhaps that also weighs in favour of keeping the conversion out of CKAN per se.

TBH I don't think it would be an issue, I think CKAN could handle that fine. I'm leaning towards recommending using the `tools` repo or similar mainly because of developer experience and centralization. I see you have plenty of modules, helpers, and documentation regarding the metadata structure on that repo, so maybe having the conversion there would prevent some code repetition on the CKAN-side + make it easier to maintain + you could integrate other data sources.

But, the advantage of having this on CKAN is that the converted metadata for datasets is available via the CKAN API.

Taking all that into consideration, I pushed the converter to the CKAN extension (see https://github.com/transport-data/tdc-data-portal/blob/4367938e7715963ecbe5bdc1951c0fe2584150b1/src/ckanext-tdc/ckanext/tdc/conversions/tdci_sdmx.py) and added some documentation to it (see https://github.com/transport-data/tdc-data-portal/blob/4367938e7715963ecbe5bdc1951c0fe2584150b1/docs/sdmx/README.md#ckan-conversion-endpoint), so in future you can decide whether to extend the converter directly on CKAN or simply create a new converter based on the CKAN API. I think it's good to have this flexibility in mind because it's hard to foresee the challenges that might arise.

___

Thank you for your detailed comments as well - it was very useful to me so that I could have a better understanding of the requirements and future plans.

**Comment by khaeru** [comment]
> I think it's good to have this flexibility in mind because it's hard to foresee the challenges that might arise.

100% agreed.

> I'd like to recommend taking a look at the following endpoints:

In order to investigate and see if we can sense some of those challenges —is there a demo instance of this API (either general, or dev/staging for TDCI) that we could use to prototype and debug code such code in the TDC tools package?

**Comment by demenech** [comment]
hello @khaeru 

Yes, feel free to use https://ckan.tdc.dev.datopian.com/

Note that you can access the API endpoints by appending `/api/3/action/{endpoint name}`

Example: https://ckan.tdc.dev.datopian.com/api/3/action/package_search
