### ISSUE TITLE
[EPIC] Adapt multiple Data Sources to be used on the project to the Metadata Schema used on the TDC data portal

### ISSUE THREAD

**Issue by Uchechukwu-Onye-Igbo** [transport-data/tdc-data-portal#16]
When I am ingesting data from multiple sources into the data portal, I want to integrate the metadata from all the sources and map them to the metadata schema used on the data portal, so that I can ensure the metadata can be integrated, standardized, searchable, and easily retrievable within the TDC data portal.

Data Sources: [Sheet](https://docs.google.com/spreadsheets/d/1L-Xsql6DZPAz-9HzmvLB6ct_MH7aA9fd/edit?gid=1950324098#gid=1950324098)

## Tasklist
* [x] #17 
* [ ] -

## Acceptance Criteria
* [ ] That the metadata from all ingested sources is integrated and mapped to the existing metadata schema used in the data portal
* [ ] That the integrated metadata is fully searchable within the data portal, allowing users to efficiently retrieve datasets based on metadata attributes
* [ ] That the aligned metadata integrates seamlessly into the data portal, appearing correctly in all relevant sections (e.g., search results, metadata displays)
* [ ] That the integrated metadata correctly reflects the original metadata from the sources, with no loss of information
* [ ] That the integrated metadata are available via the API
