### ISSUE TITLE
Adapt the Metadata of the TDC sources to the Metadata Schema used in the data portal

### ISSUE THREAD

**Issue by Uchechukwu-Onye-Igbo** [transport-data/tdc-data-portal#17]
When I am ingesting data from [TDC data sources](https://docs.google.com/spreadsheets/d/1L-Xsql6DZPAz-9HzmvLB6ct_MH7aA9fd/edit?gid=1950324098#gid=1950324098) into the data portal, I want to integrate the metadata of each of the sources and map them to the metadata schema used on the data portal, so that I can ensure the metadata can be integrated, standardized, searchable, and easily retrievable within the TDC data portal.

## Tasklist (TBD - to be included by the developer assigned)
* [x] Climatetrace - DONE
  * https://ckan.tdc.dev.datopian.com/dataset/domestic-aviation-country-emissions-climate-trace
  * https://ckan.tdc.dev.datopian.com/dataset/international-aviation-country-emissions-climate-trace
  * https://ckan.tdc.dev.datopian.com/dataset/other-transport_country-emissions-climate-trace
  * https://ckan.tdc.dev.datopian.com/dataset/railways_country-emissions-climate-trace
  * https://ckan.tdc.dev.datopian.com/dataset/road-transportation-country-emissions-climate-trace
  * https://ckan.tdc.dev.datopian.com/dataset/domestic-shipping-country-emissions-climate-trace
  * https://ckan.tdc.dev.datopian.com/dataset/international-shipping-country-emissions-climate-trace
* [x] Out World in Data -  DONE
  * [x]  Road Travel
    * https://ckan.tdc.dev.datopian.com/dataset/new-passenger-vehicle-registrations-by-type-norway
    * https://ckan.tdc.dev.datopian.com/dataset/share-of-new-passenger-vehicles-that-are-battery-electric-2019
    * https://ckan.tdc.dev.datopian.com/dataset/average-carbon-intensity-of-new-passenger-vehicles-2019
    * https://ckan.tdc.dev.datopian.com/dataset/fuel-economy-of-new-passenger-vehicles-2019
  * [x] Aviation
    * https://ckan.tdc.dev.datopian.com/dataset/global-airline-passenger-capacity-and-traffic
    * https://ckan.tdc.dev.datopian.com/dataset/share-of-airline-seats-filled-by-passengers
    * https://ckan.tdc.dev.datopian.com/dataset/per-capita-co2-emissions-from-domestic-aviation-2018
    * https://ckan.tdc.dev.datopian.com/dataset/co2-emissions-from-domestic-air-travel-2018
    * https://ckan.tdc.dev.datopian.com/dataset/share-of-global-co2-emissions-from-domestic-air-travel-2018
    * https://ckan.tdc.dev.datopian.com/dataset/per-capita-co2-emissions-from-international-aviation-2018
    * https://ckan.tdc.dev.datopian.com/dataset/co2-emissions-from-international-aviation-2018
    * https://ckan.tdc.dev.datopian.com/dataset/share-of-global-co2-emissions-from-international-aviation-2018
    * https://ckan.tdc.dev.datopian.com/dataset/per-capita-co2-emissions-from-international-passenger-flights-tourism-adjusted-2018
    * https://ckan.tdc.dev.datopian.com/dataset/per-capita-co2-emissions-from-commercial-aviation-tourism-adjusted-2018
    * https://ckan.tdc.dev.datopian.com/dataset/per-capita-co2-emissions-from-aviation-2018
    * https://ckan.tdc.dev.datopian.com/dataset/co2-emissions-from-aviation-2018
    * https://ckan.tdc.dev.datopian.com/dataset/share-of-global-co2-emissions-from-aviation-2018
    * https://ckan.tdc.dev.datopian.com/dataset/per-capita-domestic-aviation-passenger-kilometers-2018
    * https://ckan.tdc.dev.datopian.com/dataset/share-of-global-domestic-aviation-passenger-kilometers-2018
    * https://ckan.tdc.dev.datopian.com/dataset/total-domestic-aviation-passenger-kilometers-2018
    * https://ckan.tdc.dev.datopian.com/dataset/per-capita-international-aviation-passenger-kilometers-2018
    * https://ckan.tdc.dev.datopian.com/dataset/share-of-global-passenger-kilometers-from-international-aviation-2018
    * https://ckan.tdc.dev.datopian.com/dataset/total-passenger-kilometers-from-international-aviation-2018
    * https://ckan.tdc.dev.datopian.com/dataset/per-capita-passenger-kilometers-from-air-travel-2018
    * https://ckan.tdc.dev.datopian.com/dataset/share-of-global-passenger-kilometers-from-air-travel-2018
    * https://ckan.tdc.dev.datopian.com/dataset/total-passenger-kilometers-from-air-travel-2018
    * https://ckan.tdc.dev.datopian.com/dataset/tonne-kilometers-of-air-freight-2021
  * [x] Rail
    * https://ckan.tdc.dev.datopian.com/dataset/passenger-kilometers-by-rail-2021
  * [x] Energy intensity of transport
    * https://ckan.tdc.dev.datopian.com/dataset/energy-intensity-of-transport-per-passenger-kilometer-2018
  * [x] CO2 emissions from transport
    * https://ckan.tdc.dev.datopian.com/dataset/per-capita-co2-emissions-from-transport-2020
    * https://ckan.tdc.dev.datopian.com/dataset/co2-emissions-from-transport-2020 
* [x] World Bank - DONE
  * https://ckan.tdc.dev.datopian.com/dataset/container-port-traffic-teu-20-foot-equivalent-units
  * https://ckan.tdc.dev.datopian.com/dataset/railways-passengers-carried-million-passenger-km
  * https://ckan.tdc.dev.datopian.com/dataset/railways-goods-transported-million-ton-km
  * https://ckan.tdc.dev.datopian.com/dataset/rail-lines-total-route-km
  * https://ckan.tdc.dev.datopian.com/dataset/air-transport-passengers-carried
  * https://ckan.tdc.dev.datopian.com/dataset/air-transport-freight-million-ton-km
  * https://ckan.tdc.dev.datopian.com/dataset/air-transport-registered-carrier-departures-worldwide
* [x] OICA - DONE
  * https://ckan.tdc.dev.datopian.com/dataset/global-sales-statistics-2019-2023
  * https://ckan.tdc.dev.datopian.com/dataset/motorization-rate-2020---worldwide
  * https://ckan.tdc.dev.datopian.com/dataset/2023-production-statistics
* [x] ACEA - DONE
  * https://ckan.tdc.dev.datopian.com/dataset/vehicles-in-use-europe-2022
  * https://ckan.tdc.dev.datopian.com/dataset/new-car-registrations-european-union-in-july-2024
  * https://ckan.tdc.dev.datopian.com/dataset/new-commercial-vehicle-registrations-european-union-h1-2024
  * https://ckan.tdc.dev.datopian.com/dataset/new-car-registrations-by-fuel-type-european-union-in-q4-2022
  * https://ckan.tdc.dev.datopian.com/dataset/new-bus-truck-and-van-registrations-by-fuel-type-european-union-2022
  * https://ckan.tdc.dev.datopian.com/dataset/co2-emissions-from-car-production-in-the-eu
  * https://ckan.tdc.dev.datopian.com/dataset/energy-consumption-during-car-production-in-the-eu
  * https://ckan.tdc.dev.datopian.com/dataset/water-used-in-car-production-in-the-eu
  * https://ckan.tdc.dev.datopian.com/dataset/waste-from-car-production-in-the-eu 
* [ ] IRF - WorldRoadStatistics - BLOCKED - ASK JULIA
* [x] CCG - DONE
  * https://ckan.tdc.dev.datopian.com/dataset/transport-starter-data-kit---pkm
  * https://ckan.tdc.dev.datopian.com/dataset/transport-starter-data-kit---tkm
  * https://ckan.tdc.dev.datopian.com/dataset/transport-starter-data-kit---quantity
 
* [ ] ITF-OECD BLOCKED - No direct url to dataset, and database is huge
* [x] EUROSTAT - DONE
  * [x] rail
    * https://ckan.tdc.dev.datopian.com/dataset/rail-accidents-by-type-of-accident
    * https://ckan.tdc.dev.datopian.com/dataset/rail-accidents-victims-by-type-of-accident-and-category-of-persons-involved
    * https://ckan.tdc.dev.datopian.com/dataset/rail-accidents-involving-the-transport-of-dangerous-goods
    * https://ckan.tdc.dev.datopian.com/dataset/suicides-involving-railways
    * https://ckan.tdc.dev.datopian.com/dataset/passengers-transported
    * https://ckan.tdc.dev.datopian.com/dataset/international-transport-of-passengers-from-the-country-of-embarkation-to-the-reporting-country
    * https://ckan.tdc.dev.datopian.com/dataset/international-transport-of-passengers-from-the-reporting-country-to-the-country-of-disembarkation
    * https://ckan.tdc.dev.datopian.com/dataset/passenger-transport-by-type-of-transport-detailed-reporting-only
    * https://ckan.tdc.dev.datopian.com/dataset/passengers-transported-by-type-of-train-speed
    * https://ckan.tdc.dev.datopian.com/dataset/goods-transported
    * https://ckan.tdc.dev.datopian.com/dataset/length-of-railway-lines-by-maximum-permitted-speed
    * https://ckan.tdc.dev.datopian.com/dataset/length-of-railway-lines-equipped-with-the-railway-traffic-management-system-by-type-of-signalling
    * https://ckan.tdc.dev.datopian.com/dataset/level-crossings-by-type
    * https://ckan.tdc.dev.datopian.com/dataset/length-of-railway-tracks-by-electrification-of-tracks
    * https://ckan.tdc.dev.datopian.com/dataset/length-of-railway-lines-by-number-of-tracks-and-electrification-of-lines
    * https://ckan.tdc.dev.datopian.com/dataset/length-of-electrified-and-non-electrified-railway-lines-by-track-gauge
    * https://ckan.tdc.dev.datopian.com/dataset/length-of-electric-and-non-electric-railway-lines-by-nature-of-transport
    * https://ckan.tdc.dev.datopian.com/dataset/length-of-electrified-railway-lines-by-type-of-current
    * https://ckan.tdc.dev.datopian.com/dataset/international-transport-of-goods-from-the-reporting-country-to-the-unloading-country
    * https://ckan.tdc.dev.datopian.com/dataset/international-transport-of-goods-from-the-loading-country-to-the-reporting-country
    * https://ckan.tdc.dev.datopian.com/dataset/locomotives-and-railcars-by-source-of-energy
    * https://ckan.tdc.dev.datopian.com/dataset/tractive-power-of-locomotives-and-railcars-by-source-of-energy
    * https://ckan.tdc.dev.datopian.com/dataset/passenger-railway-vehicles-by-type-of-vehicle
    * https://ckan.tdc.dev.datopian.com/dataset/passenger-railway-vehicles-by-category-of-vehicle-until-2012
    * https://ckan.tdc.dev.datopian.com/dataset/seat-capacity-of-passenger-railway-vehicles-by-type-of-vehicles
    * https://ckan.tdc.dev.datopian.com/dataset/seatberth-capacity-of-passenger-railway-vehicles
    * https://ckan.tdc.dev.datopian.com/dataset/wagons-and-their-load-capacity-by-type-of-wagons
    * https://ckan.tdc.dev.datopian.com/dataset/trainsets-and-capacity-by-type-of-speed
    * https://ckan.tdc.dev.datopian.com/dataset/national-and-international-railway-passengers-transport-by-loadingunloading-nuts-2-region
    * https://ckan.tdc.dev.datopian.com/dataset/passenger-cars-in-accompanied-passenger-car-railway-transport-by-type-of-transport
    * https://ckan.tdc.dev.datopian.com/dataset/passengers-in-accompanied-passenger-car-railway-transport-by-type-of-transport
    * https://ckan.tdc.dev.datopian.com/dataset/goods-transported-by-type-of-transport
    * https://ckan.tdc.dev.datopian.com/dataset/goods-transported-by-group-of-goods-from-2008-onwards-based-on-nst-2007
    * https://ckan.tdc.dev.datopian.com/dataset/goods-transported-by-group-of-goods-until-2007-based-on-nstr
    * https://ckan.tdc.dev.datopian.com/dataset/goods-transported-by-type-of-consignment
    * https://ckan.tdc.dev.datopian.com/dataset/transit-transport-of-goods-by-loading-and-unloading-countries
    * https://ckan.tdc.dev.datopian.com/dataset/national-and-international-railway-goods-transport-by-loadingunloading-nuts-2-region
    * https://ckan.tdc.dev.datopian.com/dataset/transport-of-dangerous-goods
    * https://ckan.tdc.dev.datopian.com/dataset/goods-transported-in-intermodal-transport-units
    * https://ckan.tdc.dev.datopian.com/dataset/empty-and-loaded-intermodal-transport-units
    * https://ckan.tdc.dev.datopian.com/dataset/passenger-train-traffic-performance-by-type-of-train-speed
    * https://ckan.tdc.dev.datopian.com/dataset/hauled-railway-vehicle-traffic-performance-by-train-category-and-source-of-energy-gross-tkm-hauled
    * https://ckan.tdc.dev.datopian.com/dataset/hauled-railway-vehicle-traffic-performance-by-type-of-railway-vehicle
    * https://ckan.tdc.dev.datopian.com/dataset/train-traffic-on-the-rail-network
    * https://ckan.tdc.dev.datopian.com/dataset/train-traffic-performance-by-train-category-and-source-of-energy
  * [x] road
    * https://ckan.tdc.dev.datopian.com/dataset/persons-killed-in-road-accidents-by-age-sex-and-category-of-persons-involved
    * https://ckan.tdc.dev.datopian.com/dataset/persons-killed-in-road-accidents-by-type-of-road
    * https://ckan.tdc.dev.datopian.com/dataset/persons-killed-in-road-accidents-by-type-of-vehicle
    * https://ckan.tdc.dev.datopian.com/dataset/modal-split-of-inland-freight-transport
    * https://ckan.tdc.dev.datopian.com/dataset/modal-split-of-inland-passenger-transport-
    * https://ckan.tdc.dev.datopian.com/dataset/length-of-motorways-and-e-roads
    * https://ckan.tdc.dev.datopian.com/dataset/length-of-state-provincial-and-communal-roads
    * https://ckan.tdc.dev.datopian.com/dataset/length-of-other-roads-withinoutside-built-up-areas
    * https://ckan.tdc.dev.datopian.com/dataset/length-of-paved-and-unpaved-roads
    * https://ckan.tdc.dev.datopian.com/dataset/road-transport-equipment-stock-of-vehicles
    * https://ckan.tdc.dev.datopian.com/dataset/road-transport-equipment-load-capacities
    * https://ckan.tdc.dev.datopian.com/dataset/road-transport-equipment-new-registration-stock-of-vehicles
    * https://ckan.tdc.dev.datopian.com/dataset/road-transport-equipment-new-registration-load-capacities
    * https://ckan.tdc.dev.datopian.com/dataset/road-traffic-activity
    * https://ckan.tdc.dev.datopian.com/dataset/road-transport-measurement-passengers
    * https://ckan.tdc.dev.datopian.com/dataset/road-transport-measurement-freight
  * [x] air
    * https://ckan.tdc.dev.datopian.com/dataset/air-transport-safety
    * https://ckan.tdc.dev.datopian.com/dataset/air-transport-infrastructure-commercial-airports
    * https://ckan.tdc.dev.datopian.com/dataset/air-transport-equipment
    * https://ckan.tdc.dev.datopian.com/dataset/overview-of-the-air-passenger-transport-by-country-and-airports
    * https://ckan.tdc.dev.datopian.com/dataset/national-air-passenger-transport-by-country-and-airports
    * https://ckan.tdc.dev.datopian.com/dataset/overview-of-the-freight-and-mail-air-transport-by-country-and-airports
    * https://ckan.tdc.dev.datopian.com/dataset/national-freight-and-mail-air-transport-by-country-and-airports
    * https://ckan.tdc.dev.datopian.com/dataset/air-transport-performance-passengers
    * https://ckan.tdc.dev.datopian.com/dataset/air-transport-performance-freight-and-mail
  * [x] water
    * https://ckan.tdc.dev.datopian.com/dataset/maritime-transport-safety
    * https://ckan.tdc.dev.datopian.com/dataset/maritime-vessels-movements
    * https://ckan.tdc.dev.datopian.com/dataset/maritime-transport-passengers-detailed-annual-and-quarterly-results
    * https://ckan.tdc.dev.datopian.com/dataset/maritime-transport-goods-detailed-annual-and-quarterly-results
    * https://ckan.tdc.dev.datopian.com/dataset/inland-waterways-transport-infrastructure
    * https://ckan.tdc.dev.datopian.com/dataset/inland-waterways-transport-equipment
    * https://ckan.tdc.dev.datopian.com/dataset/inland-waterways-transport-measurement-goods-annual-data-transport
    * https://ckan.tdc.dev.datopian.com/dataset/inland-waterways-transport-measurement-goods-annual-data-container
    * https://ckan.tdc.dev.datopian.com/dataset/inland-waterways-transport-measurement-goods-annual-data-vessel
    * https://ckan.tdc.dev.datopian.com/dataset/intermodal-transport-unitisation-in-freight-transport
    * https://ckan.tdc.dev.datopian.com/dataset/index-of-inland-transport-performance-per-gdp-unit-freight
    * https://ckan.tdc.dev.datopian.com/dataset/modal-split-of-transport
    * https://ckan.tdc.dev.datopian.com/dataset/index-of-inland-transport-performance-per-gdp-unit-passenger  
* [x] JRC-IDEES - DONE
* [x] Asian Transport Outlook (ATO) - BLOCKED - metadata is not full
* [x] Kapsarc - DONE
* [x] ORNL - DONE
* [ ] GFEI (UC Davis) - NO EXISTS
* [x] GFEI (IEA) - DONE
* [x] UNECE - DONE
* [x] SLOCAT - BLOCKED - metadata is not full
* [x] CAF - Urban Mobility Observatory - DONE
* [x] UIC - DONE
* [x] IEA - no data in spreadsheet
* [x] UN SDG Indicators Database - BLOCKED - metadata is not full
* [x] GIZ GHG Inventory Data - BLOCKED - metadata is not full
* [x] Climatiq Data Explorer - BLOCKED - metadata is not full
* [x] ICCT - BLOCKED - metadata is not full

## Acceptance Criteria
* [ ] That the metadata of all TDC data sources is ingested and mapped to the existing metadata schema used in the data portal
* [ ] That the integrated metadata of all TDC data sources is fully searchable within the data portal, allowing users to efficiently retrieve datasets based on metadata attributes
* [ ] The aligned metadata of all TDC data sources integrates seamlessly into the data portal, appearing correctly in all relevant sections (e.g., search results, metadata displays)
* [ ] That the integrated metadata of all TDC data sources correctly reflects it's original metadata, with no loss of information
* [ ] That the integrated metadata of all TDC data sources are available via the API

**Comment by Mikanebu** [comment]
@Uchechukwu-Onye-Igbo This is DONE, the rest does not have metadata information.

**Comment by Mikanebu** [comment]
@Uchechukwu-Onye-Igbo List of source that we integrated:
* Climatetrace
* Out World in Data
* World Bank 
* OICA
* ACEA
* CCG
* EUROSTAT
* JRC-IDEES
* Kapsarc
* ORNL
* GFEI (IEA)
* UNECE
* CAF
* UIC

**Comment by Mikanebu** [comment]
Which source left due to lack of metadata or data: 
* IRF - WorldRoadStatistics - BLOCKED - ASK JULIA
* ITF-OECD BLOCKED - No direct url to dataset, and database is huge
* Asian Transport Outlook (ATO) - BLOCKED - metadata is not full
* GFEI (UC Davis) - NO EXISTS
* SLOCAT - BLOCKED - metadata is not full
* IEA - no data in spreadsheet
* UN SDG Indicators Database - BLOCKED - metadata is not full
* GIZ GHG Inventory Data - BLOCKED - metadata is not full
* Climatiq Data Explorer - BLOCKED - metadata is not full
*  ICCT - BLOCKED - metadata is not full

**Comment by demenech** [comment]
Docs: https://github.com/transport-data/tdc-data-portal/blob/main/src/ckanext-tdc/ckanext/tdc/data-integration/README.md

**Comment by Verena205** [comment]
GFEI data can be found here: https://zenodo.org/records/10148349

**Comment by Verena205** [comment]
@Uchechukwu-Onye-Igbo Please elaborate on the issue for SLOCAT TraKB. For now, would sugges to create one data entry for the TraKB database: https://tcc-gsr.com/3rd-edition-transport-knowledge-base-trakb/

**Comment by Verena205** [comment]
@Uchechukwu-Onye-Igbo For UN SDG Indicator Database: Please specify what information would be needed (e.g provide an empty excel overview). This way we can ask someone from TDCI or GIZ to easily fill it

**Comment by Verena205** [comment]
Regarding GHG GIZ data. Please do not include it. This is a GIZ dataset that we will upload ourselves once the platform is online

**Comment by Verena205** [comment]
@Uchechukwu-Onye-Igbo: Please do not include Climatiq. You see in the notes that it can be used for inspiration regarding labeling and is not to be integrated in the TDC

**Comment by Verena205** [comment]
ICCT data is not to be included

**Comment by Mikanebu** [comment]
@Verena205 The best way to update all sources and necessary links, please use our spreadsheet here https://docs.google.com/spreadsheets/d/1L-Xsql6DZPAz-9HzmvLB6ct_MH7aA9fd/edit?gid=1966433740#gid=1966433740. You can simply delete sources if needed. The main task here is to get source valid, and fill out metadata for each dataset with correct url for original data.

**Comment by Verena205** [comment]
In reviewing this, I also found an additional issue. All the datasets are currently listed under the organisation Transport Data Commons. However, there should be an organisation for each of the data providers (i.e. JRC-IDEES etc.), so that this is clearly reflected on the search page and the datasets can also be managed by someone from the organisation. Please adjust this accordingly. Thanks

**Comment by Verena205** [comment]
@khaeru

**Comment by Mikanebu** [comment]
@Verena205 From the beginning we decided to use 1 organization for all datasets, but distinguishing them by `Data Provider` property in our metadata section. For example, this sample https://ckan.tdc.dev.datopian.com/dataset/air-pollutants-emissions-rail-uic
```
Data Provider | UIC
-- | --
https://uic.org/
```
But if you wish to separate them via organizations, it is possible to update them.
cc @demenech @Uchechukwu-Onye-Igbo

**Comment by Verena205** [comment]
I think in this case, it will be better to seperate them by organizations as they will also be managed and updated by different users. In this case data provider and organization will be the same but in the future there might be other cases where data providers might be multiple within the same organisation

**Comment by Mikanebu** [comment]
Regarding missing metadata, if we have dataset names at least, we can create them with necessary information like you mentioned sources, indicators and so on.

**Comment by Verena205** [comment]
> cc @Verena205 Regarding missing metadata, if we have dataset names at least, we can create them with necessary information like you mentioned sources, indicators and so on.

Will aim to provide the list for UNSDG. For ATO, @khaeru might be able to help you. Regarding the other sources, please let me know if there is anything else that you need.

**Comment by Mikanebu** [comment]
@Verena205 Regarding previous comments for data sources:
1) GFEI - we use this source https://zenodo.org/records/10148349
2) ATO - we will include all 9 workbooks as resources
3) SLOCAT - we will include TraKB database: https://tcc-gsr.com/3rd-edition-transport-knowledge-base-trakb/ 
4) UN SDG Indicator Database: you can provide this sample form as in JRC source which has all the necessary columns such as dimensions, indications, source and so on. Please see this sheet https://docs.google.com/spreadsheets/d/1L-Xsql6DZPAz-9HzmvLB6ct_MH7aA9fd/edit?gid=1966433740#gid=1966433740
5) GHG GIZ - we will skip
6) Climatiq - we will skip
7) ICCT - we will skip
8) IEA - we will skip

Please confirm these above mentioned  8 sources, if we get it correctly?

Only left: 
IRF - WorldRoadStatistics - BLOCKED - ASK JULIA - We can do same for these datasets, but primary source is missing
ITF-OECD - since database is huge, we will just add link to database

**Comment by Verena205** [comment]
Dear @Mikanebu:

I confirm for 1-8. 

For 9. IRF: Please simply include as 1 entry for the database, stating that the data is available upon registration 
10. ITF-OECD: Will check similar to 4 (UN SDG) and provide an answer by tomorrow if it is possible to add links to the sources to facilitate the integration

**Comment by Marie-HD** [comment]
@Verena205 sorry Ijust found 10 minutes to have a look at the thread. It seems everything has been solved. Let me know if this would not be the case.

**Comment by Mikanebu** [comment]
@Verena205 Good! Meanwhile I will start adding other missing sources from 1-9. cc @Uchechukwu-Onye-Igbo

**Comment by khaeru** [comment]
Per ATO:

- `transport_data.adb` handles conversion of the workbooks to SDMX. [Documentation is here](https://docs.transport-data.org/en/latest/adb.html). I think it makes more sense to use and extend this code than to spend resources duplicating it.
- The ATO has an idiosyncratic data model:
  - Data and metadata are published in the ~9 large Excel workbooks mentioned.
  - Each workbook contains many sheets, each labelled with an "indicator code".
  - In general their tooling (not public) seems only able to capture 2 or sometimes 3 dimensions. So they often have "indicator codes" like "XXX-YYY-123(1): Passenger distance travelled - cars", "XXX-YYY-123(2): Passenger distance travelled - motorcycles" —in essence, manufacturing extra data flows or 'exploding' existing flows along a certain dimension.
- The `transport_data.adb` code does the following:
  - Treat each sheet (ATO "indicator code") as a distinct data flow / single data set in that data flow.
  - Extract the upstream source metadata.¹
  - Write both the SDMX data and structure information to SDMX-ML files.²
- It does not yet, but could be extended to:
  - 'Merge' together groups of ATO data flows/indicators that are identical except for an 'exploded' dimension, as mentioned above.

¹ IMO the TDC CKAN **should** list *both* the ATO *per se* and its upstream sources, and allow easy (manual or API) setting of display of links between records, such that the pages for the ATO record(s) will show "Includes data from… [links to other records]" and the pages for the original/upstream sources will show "Data from this source is also republished by… [link to ATO record]". I imagine *populating* these is out of scope for the current project, but perhaps it is in-scope to *implement* or *describe how to implement* this cross-linking feature in CKAN. (Apologies if this is already tracked in another issue; I don't have bandwidth to follow the development that closely.)

² I do not think we have a decision yet on how or where to store such files. Some possibilities:
  - The CKAN record for, e.g. an ATO "workbook" shows *both* the original file(s) and also the TDCI-formatted (=SDMX converted) versions of the same files. There would be a large number of the latter, and I imagine they would need to be distinguished from the former in the UI.
  - We set up 1 or many additional CKAN records that contain the TDCI-formatted data.

**Comment by Mikanebu** [comment]
@Verena205 
1. DONE
2. DONE
3. DONE
4. DONE
9. IRF - WorldRoadStatistics  DONE 
10. ITF-OECD - DONE
cc @Uchechukwu-Onye-Igbo

**Comment by Mikanebu** [comment]
@khaeru @Verena205 For ATO, we added 9 remote xlsx files as resources for each dataset. This is integration part where our main goal is to prepare metadata per dataset and sources. cc @Uchechukwu-Onye-Igbo
