### ISSUE TITLE
 Map Data Portal Schema to Spreadsheet Design for Enhanced Data Management and Searchability

### ISSUE THREAD

**Issue by Uchechukwu-Onye-Igbo** [transport-data/tdc-data-portal#30]
When saving or interacting with data on the data portal, I want the metadata (schema) on the data portal to be mapped to the schema design in [this spreadsheet](https://docs.google.com/spreadsheets/d/1G_Eq4T5rdolKq3uaFczbLAQfSwFzwwX9XVhjflll5gk/edit?gid=0#gid=0), so that I can effectively manage, view and search the data on the portal.

## Tasklist (TBD - updated by the developer)

* [x] Create ckanext-scheming schemas for groups, organizations, and datasets based on the metadata schema
* [x] Test all facets. Fix indexing for fields whose facet is not working as expected.

## Linked/Related Issues

- #15 
- #42 

## Acceptance Criteria

Given that I am on the data portal, I want to

* [x] be able to view, and search data according to the schema design without any conflict. 
* [x] be able to upload my data and it corresponds to the schema correctly

**Comment by demenech** [comment]
PR: https://github.com/transport-data/tdc-data-portal/pull/65

## Discussion points

- [ ] Should we make all faceted fields required?
- [ ] Should we replace "topics" with "sectors"?
- [ ] I want to suggest something. In order to enable autocomplete and enforce consistency, we could make indicator, unit, and dimensioning custom tag vocabularies.

## Still missing for this issue

- [ ] Replicate the changes to the production environment (i.e. update the prod Dockerfile)
- [ ] I changed SOLR configs directly on the SOLR UI. I have a list of changes that have to be migrated over to the custom SOLR config file when it becomes available.

## Future

- [ ] We are still waiting for the client to provide the options for some fields:
  - [ ] Geographies - We should make a CLI command to seed the options for this field
  - [ ] Modes
  - [ ] Sectors

**Comment by demenech** [comment]
FIXED. See schema at https://ckan.tdc.dev.datopian.com/api/action/scheming_dataset_schema_show?type=dataset
