### ISSUE TITLE
Implement Create, Edit, and Delete Functionality for Datasets

### ISSUE THREAD

**Issue by Uchechukwu-Onye-Igbo** [transport-data/tdc-data-portal#45]
As a data contributor to the TDC Portal, I want to be able to add new datasets, edit my existing datasets, and delete my datasets when necessary, so that I can manage the my data resources available on the platform effectively.

## Tasklist (TBD - to be added by the developer)
* [add task]

## ‼️ Important Note
Ensure the implementation of this ticket covers observations listed here https://github.com/transport-data/tdc-data-portal/issues/35#issuecomment-2348482545

## Acceptance Criteria
Given that I have access to the data portal frontend,
* [x] i am able to add a new dataset using a creation process that captures all necessary details about the data.
* [x] i am able to edit the details of my existing dataset, and changes are reflected on the platform.
* [x] i can delete a dataset, and it is removed from the platform after confirmation.
* [x] i will receive a confirmation dialog before deleting any dataset.
* [x] i will feedback messages to confirm the successful creation, editing, or deletion of datasets.

**Comment by luccasmmg** [comment]
https://github.com/transport-data/tdc-data-portal/tree/main/docs/datasets

**Comment by Uchechukwu-Onye-Igbo** [comment]
### QA Feedback

Bugs & Improvements:

* No values are showing in the dropdown for the "Define Unit" input.
* The "Geographies" and "Language" filters need further work. Typing the name of something in the list does not show up the result.
* Check all other dropdowns where users can type input to ensure they are functioning correctly.
* The "Dimensioning" field is currently required but sectors are not, but it only accepts text, makes me wonder if it should be. 
* There should be an explanation for fields like "Dimensioning" to provide better clarity to users. Maybe a text under the fields to explain them to the users.
* For datasets listed under "My Datasets," users should be able to edit them by clicking on the edit button next to it. Inform William that the "Edit" button next to the page should link to the edit screen and include a pencil icon next to the edit text for clarity or just have only the pencil icon there.
* When a dataset is created and set to private, it still displays a public tag after creation in the my dataset screen. Private datasets should not have public tags on them. This is a bug that needs fixing.

@luccasmmg

**Comment by luccasmmg** [comment]
> No values are showing in the dropdown for the "Define Unit" input.

As explained this is the intended use case, the input is there not to search but to allow the user to add multiple itens

> The "Geographies" and "Language" filters need further work. Typing the name of something in the list does not show up the result. Check all other dropdowns where users can type input to ensure they are functioning correctly.

Done

> The "Dimensioning" field is currently required but sectors are not, but it only accepts text, makes me wonder if it should be.

Removed required after talking with Demenech

> There should be an explanation for fields like "Dimensioning" to provide better clarity to users. Maybe a text under the fields to explain them to the users.

This needs to be provided by the client as currently we dont have a good definition like data_provider or url (Already checked with Demenech to confirm)

> For datasets listed under "My Datasets," users should be able to edit them by clicking on the edit button next to it. Inform William that the "Edit" button next to the page should link to the edit screen and include a pencil icon next to the edit text for clarity or just have only the pencil icon there.

Done

> When a dataset is created and set to private, it still displays a public tag after creation in the my dataset screen. Private datasets should not have public tags on them. This is a bug that needs fixing.

Done

**Comment by Uchechukwu-Onye-Igbo** [comment]
### QA Feedback

Hello @luccasmmg, kindly fix this

- when creating dataset, when i get to the last step and click submit, i get an error that reads: `Validation error: "id": The input field id was not expected`.

**Comment by Uchechukwu-Onye-Igbo** [comment]
> 1. Cant reproduce it pls send video
>    ![Image](https://github.com/user-attachments/assets/9bd6608e-f5b5-458b-9781-8a4bc375db4c)
> 2. Please give examples, my assumptions is that all datasets in `My Datasets` should be editable, and that the cases on `My Organization` should be handled by [@willy1989cv](https://github.com/willy1989cv) since i didnt write that code
> 3. Thats a bug on the `My Organization` tab, its showing draft datasets when it shouldnt
> 
> Note that the only point on my end of the work is point 1, everything else you pointed out is in the `My organization` and `My dataset` tab

hi @luccasmmg, i have sent you the video. thanks for clarifying the other points, I have directed it to the right person

**Comment by luccasmmg** [comment]
Can you please try again?

**Comment by Uchechukwu-Onye-Igbo** [comment]
> Can you please try again?

thanks @luccasmmg it now works

**Comment by nicolas-becker** [comment]
I have a few comments on the dataset creation process:
- Please change "Write a overview description of this dataset" to "Write a more detailed description of the dataset (optional)". Maybe indicate a max. character limit to the short description window, to provide guidance on what "short" means and to provide some differentiation between the two requests.
- When selecting a date for the reference period, the current date keeps appearing as selected (marked in green). Is it possible to withdraw this? I think it is a bit confusing.
-![Image](https://github.com/user-attachments/assets/80aa86e3-13c4-4318-a6a1-816c99f941b1)
- It is possible to select an earlier "To..." date than the "from" date. Can this error be catched? I was able to submit this date selection without an error displayed
- ![Image](https://github.com/user-attachments/assets/e695a687-4acc-49b9-9f57-7d554d87bb52)
- Would it be possible to write "Previous" or "Back" instead of "Prev" on the respective button? Could be misunderstood with "Preview". 
- Wrong explanatory text on Data Access field ("Data Provider...")
- There is no option to delete "Source" fields once they are added. Please add this option
- ![Image](https://github.com/user-attachments/assets/208a5e71-34ed-444d-8fde-4ccd2c4fd587)

**Comment by luccasmmg** [comment]
> Please change "Write a overview description of this dataset" to "Write a more detailed description of the dataset (optional)". Maybe indicate a max. character limit to the short description window, to provide guidance on what "short" means and to provide some differentiation between the two requests.

![image](https://github.com/user-attachments/assets/5edee34a-d582-4f70-8cef-537e84ba4467)

> When selecting a date for the reference period, the current date keeps appearing as selected (marked in green). Is it possible to withdraw this? I think it is a bit confusing.

![image](https://github.com/user-attachments/assets/dd89619e-fb30-4805-8c43-fe6b57a74af8)

> It is possible to select an earlier "To..." date than the "from" date. Can this error be catched? I was able to submit this date selection without an error displayed

![image](https://github.com/user-attachments/assets/d3d26ae4-c077-4004-951d-e289e75fe790)

> Would it be possible to write "Previous" or "Back" instead of "Prev" on the respective button? Could be misunderstood with "Preview".

![image](https://github.com/user-attachments/assets/00dc7eaf-92c7-4422-abe3-6a8424f99ece)

> Wrong explanatory text on Data Access field ("Data Provider...")

![image](https://github.com/user-attachments/assets/3c25284d-5dd8-48ed-90db-2ec5086ba55d)

> There is no option to delete "Source" fields once they are added. Please add this option

![image](https://github.com/user-attachments/assets/030deaaf-a59f-4df1-b5de-0e9fc3be83d6)

**Comment by nicolas-becker** [comment]
Thanks @luccasmmg for the fixes. Could you please also add some more guidance on the form to assist the user, specifically:

- What's the difference between Topics and Keywords.
- What is meant by "archived" in this specific context.
- Information on the "privat" checkbox disappears when the box is unchecked.
![image](https://github.com/user-attachments/assets/6b2674c2-0971-4114-92d1-e6768a93b918)
![image](https://github.com/user-attachments/assets/03cc85a7-5fbd-4dbb-b43b-0196146089d6)
- Add a link to further information on the TDC Category please. Is it possible to directly link to this section? 
![image](https://github.com/user-attachments/assets/87c86a8e-92c9-4e51-a56b-6799053de5ae)
- A default value (Public Data) should be selected for TDC Category, for cases when the user does not know which category his/her data belongs to. This could later be changed during the review, if necessary

A few more bugs detected:
- After adding a keyword via typing a word, the input field should be cleared to allow a new selection for the second keyword:
![image](https://github.com/user-attachments/assets/69b711da-8711-4d60-958d-2656fc650ed9)
- please revise the spelling of the error messages: 
![image](https://github.com/user-attachments/assets/f95436ac-b534-47c4-b573-4bdc35ca0b4e)
- the drag and drop functionality is not working for me
- it seems that it is possible to upload files larger than 30 MB, as opposed to the indication. Is there a reason to implement this limitation?
- I am getting this error message in the final step, previous to submit. Would be better to give this hint to the user after when moving from "General" to "Metadata". Also there is no field for "name", probably this refers to "slug"?
![image](https://github.com/user-attachments/assets/d9e95f3e-1152-458b-9f7a-ce2925d39a99)

**Comment by luccasmmg** [comment]
@nicolas-becker acknowledging your comments, not working on them immediately

**Comment by nicolas-becker** [comment]
@luccasmmg Okay, thank you. 

Regarding UX, we have noted a few more issues today:

- please deactivate the "Add Data" option for users without permission to do so (org members) as this creates confusion for the user. Alternatively (or even better maybe), trigger an error message saying "Your permission level for this organization (xyz) is "member" which does not allow you to add data. Please request higher permissions to the admin of your organization." Or something similar. Currently the user gets the error message at the end of the data submission process, which makes him lose time. After reveiving the error message, the user is logged out, which seems to be a bug.
- The date selection process for the reference period would benefit from the option for the user to select the year separately. Usually, the datasets will have a reference period that is way in the past, so the user will lose time selecting the date without this option.
- The language selection dropdown does not close after selection. This suggests that it is possible to add various languages, which is not the case

**Comment by luccasmmg** [comment]
> What's the difference between Topics and Keywords.

Topics have extra metadata attached to them (For example the image), can only be created by sysadmins

> What is meant by "archived" in this specific context.

That came from the metadata schema discussed with Paul, deferring to @demenech 

> Information on the "privat" checkbox disappears when the box is unchecked.

That is on purpose given that if you read the information, its only relevant for public datasets, given that private ones do not go into the approval workflow

> Add a link to further information on the TDC Category please. Is it possible to directly link to this section?

[Screencast from 2024-11-11 09-45-30.webm](https://github.com/user-attachments/assets/390d43f3-b792-4b95-afc2-79c55c8c20f3)

> A default value (Public Data) should be selected for TDC Category, for cases when the user does not know which category his/her data belongs to. This could later be changed during the review, if necessary.

![image](https://github.com/user-attachments/assets/5a539351-2c4f-4ee0-856b-ba3db345867f)

> For the further guidelines on the right side, please add a link to the "SDMX Technical Specifications" (https://sdmx.org/?page_id=5008, see the Figma example for this) and to the Help & FAQ Section of the platform: https://tdc-data-portal.vercel.app/faq#. Further remove the current placeholders and leave a comment in the docs where to edit this section, once we have the indicated documents.

![image](https://github.com/user-attachments/assets/ce9c6cf0-3fe8-4785-99ee-52d88989ce23)

> After adding a keyword via typing a word, the input field should be cleared to allow a new selection for the second keyword:

[Screencast from 2024-11-11 09-47-28.webm](https://github.com/user-attachments/assets/66ba8b51-390e-41d2-8975-025121db40bc)

> please revise the spelling of the error messages: (also replace name with slug for consistency)

What are the spelling errors misades the missing ` in cant?
![image](https://github.com/user-attachments/assets/24053491-7175-4062-b120-c013c425a42b)

> the drag and drop functionality is not working for me

Try again, i use linux so i cant actually test this, since drag and drop never works here

> it seems that it is possible to upload files larger than 30 MB, as opposed to the indication. Is there a reason to implement this limitation?

the max size was in the mockups, removed

> I am getting this error message in the final step, previous to submit. Would be better to give this hint to the user after when moving from "General" to "Metadata". Also there is no field for "name", probably this refers to "slug"?

[Screencast from 2024-11-11 10-04-22.webm](https://github.com/user-attachments/assets/0707f699-e707-4f3d-a7f4-a6a5d6f0ed28)

> When selecting All (Sectors, Modes), all options should be ticked:

[Screencast from 2024-11-11 10-05-07.webm](https://github.com/user-attachments/assets/9b92119b-06c0-4b4a-a7f8-3753f8823a19)

> After saving a Dataset as draft, and editing it again, it seems not to be possible to save as draft again (the option does not appear)

Deferring this to @willy1989cv since he was the one that built that funcionality

> please deactivate the "Add Data" option for users without permission to do so (org members) as this creates confusion for the user. Alternatively (or even better maybe), trigger an error message saying "Your permission level for this organization (xyz) is "member" which does not allow you to add data. Please request higher permissions to the admin of your organization." Or something similar. Currently the user gets the error message at the end of the data submission process, which makes him lose time. After reveiving the error message, the user is logged out, which seems to be a bug.

![image](https://github.com/user-attachments/assets/6aaacd0c-3712-4598-8934-3c20548eb2f8)

> The date selection process for the reference period would benefit from the option for the user to select the year separately. Usually, the datasets will have a reference period that is way in the past, so the user will lose time selecting the date without this option.

![image](https://github.com/user-attachments/assets/3c3fab9d-fee0-4269-9c54-fe81f11d2c11)

> The language selection dropdown does not close after selection. This suggests that it is possible to add various languages, which is not the case

[Screencast from 2024-11-11 10-20-15.webm](https://github.com/user-attachments/assets/20da5f54-949a-46b3-9273-84b7e14438de)

**Comment by nicolas-becker** [comment]
Hi @luccasmmg great, thank you!

> Topics have extra metadata attached to them (For example the image), can only be created by sysadmins

Yes, I see. And additionally, keywords will be considered in the free text search of the search bar, while topics are not, right? My question was whether it would be possible to add some further info on these two concept to the user, so he/she will know what is asked to them in both cases. Something like:
- Topic: "Select the topic(s) of your data."
- Keyword: "Select or add keywords for your data to make it easier for the community to find."

> That is on purpose given that if you read the information, its only relevant for public datasets, given that private ones do not go into the approval workflow

I understand, but I still think this option is very confusing. Could you change the configuration so it is:
- [ ] (unchecked - private) Private data
- [x] (checked - public) Publish data - Note: Before this dataset is published it will be reviewed by an Admin from your organization. You won't be able to edit it during the review.

> For the further guidelines on the right side, please add a link to the "SDMX Technical Specifications" (https://sdmx.org/?page_id=5008, see the Figma example for this) and to the Help & FAQ Section of the platform: https://tdc-data-portal.vercel.app/faq#. 

Please change the icon as the two files are not PDFs.

> What are the spelling errors misades the missing ` in cant?

Please write: "The chosen text must be URL-compatible. Please remove spaces and dots (.)"

> Try again, i use linux so i cant actually test this, since drag and drop never works here

Works now, perfect!

> I am getting this error message in the final step, previous to submit. Would be better to give this hint to the user after when moving from "General" to "Metadata". Also there is no field for "name", probably this refers to "slug"?

After a discussion with @Gutts-n on issue [102](https://github.com/transport-data/tdc-data-portal/issues/102#issuecomment-2465424287) I am not sure if the minimum of 2 characters is still correct. Could you guys please check this out and include the correct value in the error message? Thanks!

> When selecting All (Sectors, Modes), all options should be ticked

This is still not working for me

> The date selection process for the reference period would benefit from the option for the user to select the year separately. Usually, the datasets will have a reference period that is way in the past, so the user will lose time selecting the date without this option.

The "To" side is still in the old format, please also adapt, just like the "From" side

Open points would be:
- [ ] Adding info on the archived checkbox @demenech 
- [ ] Fixing the issue of saving again as draft after editing a draft data set @willy1989cv 

Everything else is perfectly fixed and working now, thanks a lot! 

Everything else is perfectly fixed and working now, thanks a lot!

**Comment by Gutts-n** [comment]
@nicolas-becker now it should work with 2 characters if the fix worked in the solr.

**Comment by willy1989cv** [comment]
>Fixing the issue of saving again as draft after editing a draft data set @willy1989cv
Fixed, please test again @nicolas-becker

**Comment by nicolas-becker** [comment]
Thank you @luccasmmg for the new fixes.

> (unchecked - private) Private data

Sorry this was a mistake from my side. It should of course say "Publish data" whether the box is checked or not. When the box is checked, the Note should appear, just like it is doing now. If you tell me where, I can try to fix this on my own.

> For that you would need to point me out to an icon

Removing the PDF icon would be fine for now, thank you.

> Please give more context a video maybe, unless you are talking about a dataset which has already been created, in that case this is a backend thing and would need to be dealt with @demenech

Sure. When I create a new dataset, this works for Sectors but not for Modes:

https://github.com/user-attachments/assets/7f174bc7-8f0c-4775-b53a-e15c4828e1ab

**Comment by nicolas-becker** [comment]
Hi @luccasmmg 

I was wondering if this 

> That is on purpose given that if you read the information, its only relevant for public datasets, given that **private ones do not go into the approval workflow**

is correct. I just submitted a private dataset for test purposes and triggered the approval process:
![Image](https://github.com/user-attachments/assets/52b17563-fc4a-4fec-843b-0f2636face7c)

If the note is valid for private _and_ public datasets, then please add it to both options. Even better it would be to have a dialog window popping up after submitting, containing this note and asking the user if he is sure he wants to proceed. This idea came to me only now so I understand if it wouldn't be possible to still implement it. But maybe to keep in mind for future updates

**Comment by nicolas-becker** [comment]
Another thing I just noticed, is that it shouldn't be possible for a user to choose an org for a dataset, for which he is not at least editor, as this triggered the same error as I had here:

> please deactivate the "Add Data" option for users without permission to do so (org members) as this creates confusion for the user. Alternatively (or even better maybe), trigger an error message saying "Your permission level for this organization (xyz) is "member" which does not allow you to add data. Please request higher permissions to the admin of your organization." Or something similar. Currently the user gets the error message at the end of the data submission process, which makes him lose time. After reveiving the error message, the user is logged out, which seems to be a bug.

So please exclude those orgs from the dropdown @luccasmmg Thanks!

**Comment by luccasmmg** [comment]
> Thank you @luccasmmg for the new fixes.
> 
> > (unchecked - private) Private data
> 
> Sorry this was a mistake from my side. It should of course say "Publish data" whether the box is checked or not. When the box is checked, the Note should appear, just like it is doing now. If you tell me where, I can try to fix this on my own.
> 
> > For that you would need to point me out to an icon
> 
> Removing the PDF icon would be fine for now, thank you.
> 
> > Please give more context a video maybe, unless you are talking about a dataset which has already been created, in that case this is a backend thing and would need to be dealt with @demenech
> 
> Sure. When I create a new dataset, this works for Sectors but not for Modes:
> 
>  Sectors-Modes.mp4

All done

**Comment by luccasmmg** [comment]
> Hi @luccasmmg
> 
> I was wondering if this
> 
> > That is on purpose given that if you read the information, its only relevant for public datasets, given that **private ones do not go into the approval workflow**
> 
> is correct. I just submitted a private dataset for test purposes and triggered the approval process: ![Image](https://private-user-images.githubusercontent.com/56161155/385674967-52b17563-fc4a-4fec-843b-0f2636face7c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE0OTMxMzAsIm5iZiI6MTczMTQ5MjgzMCwicGF0aCI6Ii81NjE2MTE1NS8zODU2NzQ5NjctNTJiMTc1NjMtZmM0YS00ZmVjLTg0M2ItMGYyNjM2ZmFjZTdjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTEzVDEwMTM1MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNkNTAyNjliMDRjNDY0NWYxZDI5NjIxZjFjZDJhNWY5YzRjMjAwZTM4NDQ2ZGU0MmE3Mzc0M2U2OWQ0Mjg5OWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.0vZVjXOgl3Lir-kevJr-aiQ5ew1BWEQPva5nTXRXXqk)
> 
> If the note is valid for private _and_ public datasets, then please add it to both options. Even better it would be to have a dialog window popping up after submitting, containing this note and asking the user if he is sure he wants to proceed. This idea came to me only now so I understand if it wouldn't be possible to still implement it. But maybe to keep in mind for future updates

Can you send a video doing that, thats not expected behaviour i believe @Gutts-n

**Comment by nicolas-becker** [comment]
@luccasmmg I just noticed that even though I get the approval request via mail, the dataset does not appear in the list of datasets pending approval. So I guess the problem is that the request is sent, not the behaviour in the backend

**Comment by nicolas-becker** [comment]
I also get a notification in the timeline:
![image](https://github.com/user-attachments/assets/f7121739-48a0-4746-a677-89f6c990fae3)

**Comment by nicolas-becker** [comment]
Here is the video:

https://github.com/user-attachments/assets/a35ca542-620a-4ceb-92c3-00c94a6122d4

**Comment by nicolas-becker** [comment]
@luccasmmg 

> All done

Your latest fixes are not working for me yet

**Comment by luccasmmg** [comment]
Deployed now @nicolas-becker

**Comment by nicolas-becker** [comment]
HI @willy1989cv adding to this previous comment: https://github.com/transport-data/tdc-data-portal/issues/45#issuecomment-2469865862

Belén just informed me that she is getting an error when trying to safe a dataset as draft:
![Image](https://github.com/user-attachments/assets/5f87833c-d06c-41b4-b18c-5d71afccb58f)

**Comment by nicolas-becker** [comment]
@luccasmmg 

> Deployed now @nicolas-becker 

nice, this is working now. Could you please just remove the ":" from "Publish data:" when the checkbox is not selected/ the note is not displayed? Thanks!

**Comment by willy1989cv** [comment]
> @willy1989cv thanks, the option does appear now, but I am still not able to safe the changes. Although I get a success message and the date of the data set is updated, I still see the old information when I enter the edit mode again.

@nicolas-becker please check again.this is now fixed

**Comment by nicolas-becker** [comment]
Hi @willy1989cv this is working now for me. But Belén is still facing the same error when trying to create a draft: https://github.com/transport-data/tdc-data-portal/issues/45#issuecomment-2473847696

She as editor rights for the GIZ org

**Comment by Uchechukwu-Onye-Igbo** [comment]
> Hi @willy1989cv this is working now for me. But Belén is still facing the same error when trying to create a draft: [#45 (comment)](https://github.com/transport-data/tdc-data-portal/issues/45#issuecomment-2473847696)
> 
> She has editor rights for the GIZ org.
> 
> Strangely, it apppears the dataset is sent for submission when she hit `save draft` and gets the error

hello @willy1989cv  please take a look at this

**Comment by luccasmmg** [comment]
@nicolas-becker you should probably read thru the documentation https://github.com/transport-data/tdc-data-portal/tree/main/docs/technical-documentation, the code for this form can be found in the `src/components/dataset/form` folder and its just standard react code.

> I've also flagged in a few related issues that having the Name field as input is not optimal from a user perspective. I understand of course that it is necessary to keep it but would it be possible to hide it/ not ask the user to modify it and provide it only as information to the user?

Are you 100% sure? I can do that, but that could cause some confusion

**Comment by nicolas-becker** [comment]
> https://github.com/transport-data/tdc-data-portal/tree/main/docs/technical-documentation, the code for this form can be found in the src/components/dataset/form folder and its just standard react code

Just had a look, very nice!

> Are you 100% sure? I can do that, but that could cause some confusion

I guess it would create less confusion than to ask for a Title and a Name. But I agree to keep it this way for now and wait for the actual user feedback before doing any modifications. Thanks for your feedback!

**Comment by luccasmmg** [comment]
@nicolas-becker ok, in that case just for your information, all it would have to be done is 

1. https://github.com/transport-data/tdc-data-portal/blob/main/frontend/src/components/dataset/form/General.tsx#L110 add a "hidden" to the className here
2. Comment out this line in the test pipeline https://github.com/transport-data/tdc-data-portal/blob/main/frontend/cypress/e2e/datasets_crud.cy.js#L161

**Comment by nicolas-becker** [comment]
Hi @luccasmmg, I am currently trying to update a dataset and noticed that in the geography field the number of countries to be displayed seems to be limited to 5:

![Image](https://github.com/user-attachments/assets/1890f836-1ed5-4a7d-b93c-57f17b97d35c)

In the screenshot you see that Hungary is not displayed anymore

I did some more testing and it seems like the visible part of the input field is limited. You see that for Gabun it only shows the G:

![Image](https://github.com/user-attachments/assets/7be5f42c-727d-45a2-a739-0f8d8db22b72)

Also I just got an unknown error again when trying to submit this dataset (@demenech ):

![Image](https://github.com/user-attachments/assets/aaf0b16b-f2a7-4baf-93d9-99fad9a271dc)

(this happened even after deleting the countries again. The datset I tested is "test-error-2")

**Comment by luccasmmg** [comment]
> In the screenshot you see that Hungary is not displayed anymore I did some more testing and it seems like the visible part of the input field is limited. You see that for Gabun it only shows the G:

Yes, thats on purpose, otherwise if you select too many countries it breaks the entire screen

**Comment by nicolas-becker** [comment]
> Yes, thats on purpose, otherwise if you select too many countries it breaks the entire screen

Hi @luccasmmg thanks for getting back on this. In which sense will it break the screen? There is pretty much space left on the text input field. Would it be possible to adapt the text shown to the screen size or show something like "..." before hiding the remaining input? Otherwise it currently looks like a bug...

**Comment by demenech** [comment]
@nicolas-becker

I'm looking into this error you had, but unfortunately, it seems like the CKAN service restarted and I lost the logs of that time.

Can you please check if this still happens?

If yes, please leave this dataset as it is.

Thanks!

**Comment by nicolas-becker** [comment]
Hi @demenech , it seems to be working again.

**Comment by demenech** [comment]
> it seems to be working again.

@nicolas-becker I suspect a restart might have happened around that time. I updated the dev deployment settings to avoid this, please let me know if this happens again. Thanks.

**Comment by luccasmmg** [comment]
> Hi @luccasmmg thanks for getting back on this. In which sense will it break the screen? There is pretty much space left on the text input field. Would it be possible to adapt the text shown to the screen size or show something like "..." before hiding the remaining input? Otherwise it currently looks like a bug...

Changed to use overflow

[Screencast from 2024-12-03 09-59-49.webm](https://github.com/user-attachments/assets/cd060e31-cba5-4651-a412-0efea6f2dc8e)

**Comment by nicolas-becker** [comment]
Perfect, thanks @luccasmmg !
