### ISSUE TITLE
[EPIC] Implement the Functional Logic of Organization and Groups Management (CRUD)

### ISSUE THREAD

**Issue by Uchechukwu-Onye-Igbo** [transport-data/tdc-data-portal#48]
As a user of the TDC portal, I want to be able to create, edit, manage, and delete organizations and groups, as well as add or remove members within organizations, so that I can effectively control and maintain dataset groups, organizations and their membership on the portal.

## Tasklist (TBD - updated by the developer)
* [x] #60 
* [x] #61 
* [x] #62 
* [x] #63 
* [add tasks]

##Acceptance Criteria
Given that I am a user and have access to the portal,
* [x] I want to be able to create a new organization on the portal.
* [x] I can edit the details of organisations I created.
* [x] I can view and manage the list of members within my organization
* [x] I can add new members to and remove existing members to my organization.
* [x] I can delete my organization if needed.
* [x] I can create and delete dataset groups

**Comment by nicolas-becker** [comment]
I have a question on the process of adding members that are not yet registered on the platform. It is possible to enter new email addresses in the `add member` form to an organization. Even though this yields an error message, an invitation is sent to the indicated mail address to create a profile on the CKAN platform. But this newly created user profile will not be valid for the TDC platform, as this only accepts GitHub accounts, right?

**Comment by Uchechukwu-Onye-Igbo** [comment]
> I have a question on the process of adding members that are not yet registered on the platform. It is possible to enter new email addresses in the `add member` form to an organization. Even though this yields an error message, an invitation is sent to the indicated mail address to create a profile on the CKAN platform. But this newly created user profile will not be valid for the TDC platform, as this only accepts GitHub accounts, right?

Hi @nicolas-becker 

I just tried inviting a member who is not registered on the platform to an org, I got an error (expected). But I checked the email account, there was no invite to come join the org (this is also expected). I cannot reproduce this.

Regarding if the user can create a valid account. when a user tries to join TDC, they have to use a GitHub account. it is up to them to choose which of their GitHub accounts they want to use. So, it is not compulsory that the user must create an account using the email by which they were invited.

when a user creates an account after an invite (speaking in terms of an invite to join the platform), they are not automatically added to an org. They have to request to be added to an org - after they have signed up.

I hope this clears you

**Comment by nicolas-becker** [comment]
Hi @Uchechukwu-Onye-Igbo, thanks for the reply and for the clarification.

That's strange. I got this email when adding my GIZ account to an organization:

![Image](https://github.com/user-attachments/assets/65256117-4579-4e2c-a6b2-937d49a10fa0)

My question was rather, how this newly created user (in this case `nicolas-becker-5392`) would interact with the platform after registering. But as this email invite shouldn't have been sent, I guess the question is obsolete?

**Comment by Uchechukwu-Onye-Igbo** [comment]
> Hi [@Uchechukwu-Onye-Igbo](https://github.com/Uchechukwu-Onye-Igbo), thanks for the reply and for the clarification.
> 
> That's strange. I got this email when adding my GIZ account to an organization:
> 
> ![Image](https://github.com/user-attachments/assets/65256117-4579-4e2c-a6b2-937d49a10fa0)
> 
> My question was rather, how this newly created user (in this case `nicolas-becker-5392`) would interact with the platform after registering. But as this email invite shouldn't have been sent, I guess the question is obsolete?

Hi @nicolas-becker we are working on #184 to fix the behaviour.

**Comment by nicolas-becker** [comment]
Alright, thanks for the hint @Uchechukwu-Onye-Igbo . In that case I'll move this issue to done
