### ISSUE TITLE
Implement Frontend logic for Dataset Request Approval

### ISSUE THREAD

**Issue by Uchechukwu-Onye-Igbo** [transport-data/tdc-data-portal#49]
**User 1:**
As a data contributor on the TDC portal, I want to submit my datasets intended to be public for review/approval by the admin, so that I can provide valuable data that may be made available on the portal for general consumption.

**User 2:**
As an admin on the TDC portal, I want to be able to view dataset requests submitted by data contributors, and either approve or reject them with comments, so that I can ensure only appropriate and quality datasets are made available on the portal.

## Tasklist (TBD - updated by the developer)
* [add tasks]

## Acceptance Criteria

**User 1:**
Given that I am a data contributor on the portal and have made a dataset approval request;
* [ ] I can view all my pending requests on "My dataset" and "my organisation" page of the dashboard.
* [ ] Other user in my organisation can see the dataset request I made in their respective "my organisation" page
* [ ] I cannot edit the dataset when it is in review
* [ ] I will get update in my newsfeed when my dataset has been a approved or rejected
* [ ] I can view a label that reads "draft" on my datasets that are in draft

**User 2:**
Given that I am an admin of the portal and have access to the backend of the portal,
* [ ] I can view all pending dataset requests on the portal.
* [ ] I can approve/reject a dataset request by click of a button, making it live on the portal.
* [ ] When I reject a dataset request, I can provide a comment explaining the decision.
* [ ] My decision on any data request will be notified the data contributors. 
* [ ] I will receive an email about the data request from data contributors

**Comment by Uchechukwu-Onye-Igbo** [comment]
### Points from meeting

* send an email to a user when a data is rejected. it should have the link to the dataset as well and the email address of the person who rejected it.
* When datasets are created private, they are approved. only when they are set to public that they will be sent to review

**Comment by Gutts-n** [comment]
@Uchechukwu-Onye-Igbo and @osahon-okungbowa can an org admin edit the requested dataset? A use case for it is, if there is a typo in some description and it's just it that is blocking the approval of the dataset, and the admin doesn't want to send a message to the user to change this description because is a minor change, he wants to change the description and approved based on his change.

**Comment by osahon-okungbowa** [comment]
@Gutts-n the answer is Yes👍 The org admin or sysadmin can edit the dataset being reviewed

**Comment by Uchechukwu-Onye-Igbo** [comment]
### Additional Improvements

- Remove my discussions tab and repurpose it for Approvals
- There should be a “categories” list like we have in the newsfeed tab. It should have the status of approval; all, approved, pending and rejected. The tab should be available to all users

@Gutts-n

**Comment by Gutts-n** [comment]
@Uchechukwu-Onye-Igbo and @osahon-okungbowa I don't think we should present approved datasets on the dataset requests tab, I think it will pollute the tab with so many datasets for the admins (mainly for the sysadmins), it's just a suggestion 👍 .

**Comment by Uchechukwu-Onye-Igbo** [comment]
> [@Uchechukwu-Onye-Igbo](https://github.com/Uchechukwu-Onye-Igbo) and [@osahon-okungbowa](https://github.com/osahon-okungbowa), I don't think we should present approved datasets on the dataset requests tab. It will pollute the tab with so many datasets for the admins (mainly for the sysadmins). It's just a suggestion 👍 .
> 
> Why to present the dataset approvals to all users? If a user is a member he can't do anything with the dataset because he can't edit and neither approve or reject. I'm presenting just for orgs' admins and editors.

my take on this;
1. I think if they can see when the dataset is pending approval, i think it makes sense they know when it is approved. Please NOTE that we are not calling the tab "Dataset request". we are calling it "Dataset Approval"

2. i think i agree with this. members with no org privileges' should not see them, since they cannot create or edit datasets themselves.

**Comment by osahon-okungbowa** [comment]
> @Uchechukwu-Onye-Igbo and @osahon-okungbowa, I don't think we should present approved datasets on the dataset requests tab. It will pollute the tab with so many datasets for the admins (mainly for the sysadmins). It's just a suggestion 👍 .
> 
> Why to present the dataset approvals to all users? If a user is a member he can't do anything with the dataset because he can't edit and neither approve or reject. I'm presenting just for orgs' admins and editors.

@Gutts-n hold off on these parts till we discuss.

**Comment by demenech** [comment]
Moving to QA.

Docs can be found at: https://github.com/transport-data/tdc-data-portal/tree/main/docs/approval-workflow

**Comment by Uchechukwu-Onye-Igbo** [comment]
### QA Feedback

Hello @Gutts-n, some issues,

- I created a dataset with TDC harmonized and set it to public, it did not go to approval. It just became public.
- ![Image](https://github.com/user-attachments/assets/403a16ef-657e-4f60-8a7b-4b973dc281af)

Please take a look at this and fix it because this is a blocker for me to test other things in this issue.

**Comment by Uchechukwu-Onye-Igbo** [comment]
> ### QA Feedback
> Hello [@Gutts-n](https://github.com/Gutts-n), some issues,
> 
> * I created a dataset with TDC harmonized and set it to public, it did not go to approval. It just became public.
> * ![Image](https://github.com/user-attachments/assets/403a16ef-657e-4f60-8a7b-4b973dc281af)
> 
> Please take a look at this and fix it because this is a blocker for me to test other things in this issue.

this now works. thanks for the help @demenech

**Comment by nicolas-becker** [comment]
@Gutts-n @willy1989cv 

When rejecting a dataset it still appears in the Dataset Approval list, but with the status "Rejected", which is the expected behaviour. But I am also able to "Edit" the dataset and the `Submit` button is activated, although nothing happens when I select it. 

My expectation would be that the submit button is deaktivated (grey or disppeared) or that I can revoke my decision by submitting the dataset after editing it. Both options would be fine for me, but I think the second option might lead to further follow-up questions (e.g., how to prevent duplicates if the user requested a new dataset after the initial rejection).

**Comment by Gutts-n** [comment]
@nicolas-becker are your user a sysadmin or organization admin? When a dataset is rejected and you are an admin you can edit it and change it to public.

**Comment by nicolas-becker** [comment]
@Gutts-n I am a Sysadmin yes. How can I accept a dataset after rejection? I can't find the option...

**Comment by Gutts-n** [comment]
@nicolas-becker, In this case, you can just change the dataset to public, as you are an admin it won't enter on the approval flow again.

**Comment by nicolas-becker** [comment]
Hi @Gutts-n I just did so and the dataset kept appearing as rejected and won't let me decide again:

![image](https://github.com/user-attachments/assets/1605d8c3-3d26-4bea-80bc-550abe7ea3c0)

**Comment by Gutts-n** [comment]
@nicolas-becker, in this case, the dataset is public so the rejected label can't affect anything on it, but @demenech is looking at why the status didn't change when you turned it to public on the backend.

**Comment by nicolas-becker** [comment]
@Gutts-n okay, I see that the datset is now published and can be located via the data set search. To make this process more clear, it would be better to keep the `Accept dataset` button when editing the dataset after rejection. Also, please visually deactivate the submit button  when it is not possible to click it, just as Luccas did for the `Add Data` button for member users:
![image](https://github.com/user-attachments/assets/5789ba60-3633-438a-a07c-16b8f0e481ae)

**Comment by Gutts-n** [comment]
Documentation: https://github.com/transport-data/tdc-data-portal/blob/main/docs/approval-workflow/README.md

**Comment by Gutts-n** [comment]
@nicolas-becker done!

**Comment by nicolas-becker** [comment]
@Gutts-n perfect, the `Approve Dataset` option does appear again. For this particular case, where I had submitted/published the dataset previously, I observe the following error when trying to accept the dataset now.
https://github.com/user-attachments/assets/9d4e6c37-65d1-42bb-ba0d-add728b75825

To prevent this kind of error, I think it would be better if you could deactivate the submit button:
![image](https://github.com/user-attachments/assets/f5e4c4d1-e5c9-48a2-b3bd-96b8a39f3572)

But please correct me if I am getting the logic wrong. Thanks!

**Comment by Gutts-n** [comment]
@nicolas-becker I pushed a change to the backend to now when an admin user changes the dataset to public and it is rejected we remove the rejected and its reason, then this approval button to the rejected dataset won't be used since we are erasing it.

Please test it and give me feedback.

**Comment by nicolas-becker** [comment]
Hi @Gutts-n 

This seems to work now. But I am still not sure about the entire process. Maybe we can touch upon this in the discussion later?

**Comment by Gutts-n** [comment]
hey @nicolas-becker I saw your comment after the meeting, what are your doubts?

**Comment by nicolas-becker** [comment]
Hi @Gutts-n no worries, I was wondering if we could quickly got through the dataset approval process with the different interaction options. Specfically I am not sure about the difference between the admin options to accept a datset sent for approval and submitting the dataset after review. Thank you!

**Comment by Uchechukwu-Onye-Igbo** [comment]
> Hi @Gutts-n no worries, I was wondering if we could quickly got through the dataset approval process with the different interaction options. Specfically I am not sure about the difference between the admin options to accept a datset sent for approval and submitting the dataset after review. Thank you!

@Gutts-n please take a look

**Comment by nicolas-becker** [comment]
@Gutts-n thanks for going through the process again.

> Admins can edit a dataset that is "pending", and editors can't.

This is exactly the point that I am not sure about. I the admin edits a dataset that is pending approval, and submits the changes, this is equal to an approval of the dataset, right? Will user who initially submitted this dataset be notifyed of this process?

**Comment by Gutts-n** [comment]
@nicolas-becker, no, it is not. The admin can edit the dataset but keep it as "pending." The dataset is approved or rejected when he clicks on the approvals buttons.

**Comment by Gutts-n** [comment]
@nicolas-becker a use case would be for the admin to see that there are two fields to be filled in order to approve the dataset, but he can only edit one of them at the moment because he needs to go after the information to fill in the other field, or he needs to leave and come back later, in which case he would save the dataset and then come back to finish the job so that after updating it and making it ready for approval, he can approve it.

Or just fill in a field and reject the user fill in the other one.

**Comment by nicolas-becker** [comment]
@Gutts-n I understand, so this would sort of act as a "save draft" function in this context. Thank you for the explanation!
