### ISSUE TITLE
Implement a the ability to Manage Members of Organizations within the User Dashboard

### ISSUE THREAD

**Issue by Uchechukwu-Onye-Igbo** [transport-data/tdc-data-portal#61]
As an organization admin, I want to invite, remove and specify roles for members of my organization, so that I can control who is part of the organization and assign roles as necessary.

## Tasklist (TBD - updated by the developer)
* [add tasks]

## Acceptance Criteria
Given that I logged in into the user dashboard,
* [x] I can view all current members of my organization.
* [x] I can add new members by entering their email addresses.
* [x] I can remove members from the organization.
* [x] I can assign or update user roles in my organization.
* [x] I can see the changes I made to the member list reflected immediately.
* [x] I can see a confirmation prompt when removing members.

**Comment by luccasmmg** [comment]
@osahon-okungbowa 

I was planning on writing the docs only after @muhammad-hassan11 finished the list since otherwise they are not very coherent, but since you asked i wrote them now

https://github.com/transport-data/tdc-data-portal/tree/main/docs/orgs
https://github.com/transport-data/tdc-data-portal/tree/main/docs/topics

You can test by following the docs
