### ISSUE TITLE
Implement the functionality to Delete Groups and Organizations

### ISSUE THREAD

**Issue by Uchechukwu-Onye-Igbo** [transport-data/tdc-data-portal#63]
As a user, I want to my delete organizations or groups, so that I can remove outdated or irrelevant entities from the portal.

## Tasklist (TBD - updated by the developer)
* [add tasks]

## Acceptance Criteria
Given that I logged in into the user dashboard,
* [x] I can select an organization or group to delete.
* [x] I get a delete confirmation dialog to confirm the deletion of the organization or group.
* [x] I can see that upon deletion, the group or organization is removed from the list of groups/organizations.
* [x] I can see a success message after I have taken the deletion action

**Comment by osahon-okungbowa** [comment]
@luccasmmg how to test this.

Also, please include link to the documentation/user guide

**Comment by luccasmmg** [comment]
@osahon-okungbowa 

I was planning on writing the docs only after @muhammad-hassan11 finished the list since otherwise they are not very coherent, but since you asked i wrote them now

https://github.com/transport-data/tdc-data-portal/tree/main/docs/orgs
https://github.com/transport-data/tdc-data-portal/tree/main/docs/topics

You can test by following the docs

**Comment by luccasmmg** [comment]
@nicolas-becker thats technically default ckan behaviour, the idea is that all deletes are just soft deletes, so as not to break relations

**Comment by nicolas-becker** [comment]
@luccasmmg thanks for clarifying! So this means that once a URL is disgnated, it will be blocked "for ever", even when we delete the object on the portal? Just to make sure I understood correctly

**Comment by luccasmmg** [comment]
You can eventually purge it, if not it's going to be blocked
