### ISSUE TITLE
Investigate and implement conversion to application-specific SDMX metadata structure

### ISSUE THREAD

**Issue by Uchechukwu-Onye-Igbo** [transport-data/tdc-data-portal#78]
When importing CKAN datasets into another platform, I want to have the option to get responses following the application-specific SDMX metadata structure, so that systems are interoperable and the level of required transformation is minimum or none. 

## Taskls

- [x] Investigate ESMS
- [x] Investigate the TDCI SDMX metadata structure
- [x] Add new fields to the CKAN metadata schema to make the conversion to TDCI SDMX possible, if necessary
- [x] Create an extendable converter that allows the exporting of CKAN datasets metadata as TDCI SDMX metadata structure 
- [x] Create documentation explaining the relationship between the CKAN metadata schema, TDCI SDMX MS and ESMS
- [x] Create documentation explaining how the converter works and how it can be extended

## Acceptance Criteria

- [ ] There is documentation explaining the relationship between the CKAN metadata schema, the TDCI SDMX metadata structure, and the ESMS metadata structure
- [ ] The TDC extension supports a converter to TDCI application-specific SMDX metadata structure that can be easily extended together with the metadata schema, and there is documentation on how converter extension works
- [ ] The CKAN metadata schema is updated with fields that are necessary in order to support the TDCI SDMX MS conversion

**Comment by demenech** [comment]
PR: https://github.com/transport-data/tdc-data-portal/pull/114

Moving to peer review.

**Comment by osahon-okungbowa** [comment]
@demenech please how can i QA this?
There are no links to a documentation, implementation or any links on the issue

**Comment by demenech** [comment]
Docs: https://github.com/transport-data/tdc-data-portal/blob/main/docs/sdmx/README.md

In order to do QA, you can replace the dataset ID on the following URL: https://ckan.tdc.dev.datopian.com/api/3/action/package_show?id=my-dataset-qa&output_format=tdci-sdmx

Note that the response will be following these guidelines: https://github.com/transport-data/tools/pull/21/files#diff-a920973cf3c3bdb7578f9a3e8784fb624988297308cd07162659a7da2dceb014R21

CC: @osahon-okungbowa @Uchechukwu-Onye-Igbo

**Comment by nicolas-becker** [comment]
@khaeru
